import { CarModelRecord, FuelType } from '../types';

export const FUEL_TYPE_CONFIG: Record<FuelType, {
  label: string;
  emoji: string;
  bgColor: string;
  textColor: string;
  borderColor: string;
  iconName: string;
}> = {
  Petrol: {
    label: 'Petrol',
    emoji: '⛽',
    bgColor: 'bg-amber-50 dark:bg-amber-950/40',
    textColor: 'text-amber-700 dark:text-amber-400',
    borderColor: 'border-amber-300 dark:border-amber-700/60',
    iconName: 'Fuel',
  },
  Diesel: {
    label: 'Diesel',
    emoji: '🛢️',
    bgColor: 'bg-blue-50 dark:bg-blue-950/40',
    textColor: 'text-blue-700 dark:text-blue-400',
    borderColor: 'border-blue-300 dark:border-blue-700/60',
    iconName: 'Droplets',
  },
  CNG: {
    label: 'CNG',
    emoji: '🟢',
    bgColor: 'bg-emerald-50 dark:bg-emerald-950/40',
    textColor: 'text-emerald-700 dark:text-emerald-400',
    borderColor: 'border-emerald-300 dark:border-emerald-700/60',
    iconName: 'Wind',
  },
  EV: {
    label: 'Electric (EV)',
    emoji: '⚡',
    bgColor: 'bg-violet-50 dark:bg-violet-950/40',
    textColor: 'text-violet-700 dark:text-violet-400',
    borderColor: 'border-violet-300 dark:border-violet-700/60',
    iconName: 'Zap',
  },
  Hybrid: {
    label: 'Strong / Mild Hybrid',
    emoji: '🔋',
    bgColor: 'bg-teal-50 dark:bg-teal-950/40',
    textColor: 'text-teal-700 dark:text-teal-400',
    borderColor: 'border-teal-300 dark:border-teal-700/60',
    iconName: 'BatteryCharging',
  },
  LPG: {
    label: 'LPG AutoGas',
    emoji: '🔥',
    bgColor: 'bg-orange-50 dark:bg-orange-950/40',
    textColor: 'text-orange-700 dark:text-orange-400',
    borderColor: 'border-orange-300 dark:border-orange-700/60',
    iconName: 'Flame',
  },
};

export const INITIAL_CAR_MODELS: CarModelRecord[] = [
  // ==========================================
  // MARUTI SUZUKI
  // ==========================================
  {
    id: 'model-maruti-swift',
    make: 'Maruti Suzuki',
    model: 'Swift',
    category: 'Hatchback',
    variants: ['LXi', 'VXi', 'VXi (O)', 'ZXi', 'ZXi Plus', 'ZXi CNG', 'VXi CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L 3-Cyl Z-Series / DualJet (1197 cc)',
    engineOilSpec: '3.1 Litres • 0W-16 / 0W-20 Synthetic',
    coolantSpec: '4.2 Litres • Long Life Coolant',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
    notes: 'High volume workshop car. Common work: front brake pads, clutch overhaul, periodic 10k service.',
  },
  {
    id: 'model-maruti-baleno',
    make: 'Maruti Suzuki',
    model: 'Baleno',
    category: 'Hatchback',
    variants: ['Sigma', 'Delta', 'Zeta', 'Alpha', 'Delta CNG', 'Zeta CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L 4-Cyl K12N DualJet (1197 cc)',
    engineOilSpec: '3.3 Litres • 0W-16 Synthetic',
    coolantSpec: '4.5 Litres',
    recommendedPsi: '30 PSI (Front) / 30 PSI (Rear)',
    isPopular: true,
    notes: 'Premium hatchback. Common parts: LED headlamp assembly, stabilizer links, cabin AC filter.',
  },
  {
    id: 'model-maruti-brezza',
    make: 'Maruti Suzuki',
    model: 'Brezza',
    category: 'Compact SUV',
    variants: ['LXi', 'VXi', 'ZXi', 'ZXi Plus', 'LXi CNG', 'VXi CNG', 'ZXi CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.5L 4-Cyl K15C Smart Hybrid (1462 cc)',
    engineOilSpec: '3.6 Litres • 0W-16 / 0W-20 Synthetic',
    coolantSpec: '5.0 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Compact SUV with Smart Hybrid assist. Brake rotor skimming and suspension bush inspection.',
  },
  {
    id: 'model-maruti-dzire',
    make: 'Maruti Suzuki',
    model: 'Dzire',
    category: 'Sedan',
    variants: ['LXi', 'VXi', 'ZXi', 'ZXi Plus', 'VXi CNG', 'ZXi CNG', 'Tour S CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L Z12E / K12M (1197 cc)',
    engineOilSpec: '3.1 Litres • 0W-16 Synthetic',
    coolantSpec: '4.2 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
    notes: 'Massive fleet & private volume. High demand for clutch plates, brake pads & periodic maintenance.',
  },
  {
    id: 'model-maruti-grand-vitara',
    make: 'Maruti Suzuki',
    model: 'Grand Vitara',
    category: 'SUV',
    variants: ['Sigma', 'Delta', 'Zeta', 'Alpha', 'Alpha AWD', 'Delta CNG', 'Zeta CNG', 'Zeta+ Strong Hybrid', 'Alpha+ Strong Hybrid'],
    fuelTypes: ['Petrol', 'CNG', 'Hybrid'],
    engineDisplacement: '1.5L K15C Mild Hybrid / 1.5L Atkinson Cycle Strong Hybrid (1490 cc)',
    engineOilSpec: '3.6L (Mild) / 3.8L (Strong Hybrid) • 0W-16 Synthetic',
    coolantSpec: '5.5 Litres (Dual Inverter Cooling)',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Mid-size SUV with Strong Hybrid & AllGrip AWD options. Inspect high-voltage hybrid battery air ducts.',
  },
  {
    id: 'model-maruti-ertiga',
    make: 'Maruti Suzuki',
    model: 'Ertiga',
    category: 'MUV',
    variants: ['LXi', 'VXi', 'ZXi', 'ZXi Plus', 'VXi CNG', 'ZXi CNG', 'Tour M CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.5L K15C Smart Hybrid (1462 cc)',
    engineOilSpec: '3.6 Litres • 0W-16 Synthetic',
    coolantSpec: '5.2 Litres',
    recommendedPsi: '34 PSI (Front) / 36 PSI (Rear full load)',
    isPopular: true,
    notes: '7-seater MUV. Frequent rear brake shoe replacement and rear suspension shocker inspection.',
  },
  {
    id: 'model-maruti-fronx',
    make: 'Maruti Suzuki',
    model: 'Fronx',
    category: 'Compact SUV',
    variants: ['Sigma', 'Delta', 'Delta Plus', 'Delta+ Turbo', 'Zeta Turbo', 'Alpha Turbo', 'Sigma CNG', 'Delta CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L K12N / 1.0L Boosterjet Turbo (998 cc)',
    engineOilSpec: '3.2 Litres • 0W-20 Synthetic',
    coolantSpec: '4.8 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-maruti-wagonr',
    make: 'Maruti Suzuki',
    model: 'Wagon R',
    category: 'Hatchback',
    variants: ['LXi 1.0', 'VXi 1.0', 'ZXi 1.2', 'ZXi+ 1.2', 'LXi CNG', 'VXi CNG'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.0L K10C / 1.2L K12N (998 cc - 1197 cc)',
    engineOilSpec: '2.8L (1.0L) / 3.1L (1.2L) • 0W-20',
    coolantSpec: '3.8 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
  },

  // ==========================================
  // HYUNDAI
  // ==========================================
  {
    id: 'model-hyundai-creta',
    make: 'Hyundai',
    model: 'Creta',
    category: 'SUV',
    variants: ['E', 'EX', 'S', 'S(O)', 'SX', 'SX Tech', 'SX(O)', 'SX(O) Turbo DCT', 'N-Line N8', 'N-Line N10', 'Knight Edition'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L MPi Petrol (1497 cc) / 1.5L U2 CRDi Diesel (1493 cc) / 1.5L Turbo GDi (1482 cc)',
    engineOilSpec: '3.8L Petrol (5W-30 / 0W-20) • 4.8L Diesel (5W-30 C3 Low-SAPS DPF safe)',
    coolantSpec: '5.8 Litres (Petrol) / 6.5 Litres (Diesel)',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Top seller. Critical: Use Low-SAPS C3 engine oil for BS6 Diesel DPF protection. Check DEF level.',
  },
  {
    id: 'model-hyundai-venue',
    make: 'Hyundai',
    model: 'Venue',
    category: 'Compact SUV',
    variants: ['E', 'S', 'S(O)', 'S+', 'SX', 'SX(O)', 'SX(O) Dual Tone', 'N-Line N6', 'N-Line N8', 'Knight Edition'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.2L Kappa MPi / 1.0L Turbo GDi (998 cc) / 1.5L U2 CRDi (1493 cc)',
    engineOilSpec: '3.4L (1.2L) / 3.6L (1.0L Turbo) / 4.5L (1.5L Diesel) • 5W-30 Synthetic',
    coolantSpec: '5.0 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-hyundai-i20',
    make: 'Hyundai',
    model: 'i20',
    category: 'Hatchback',
    variants: ['Era', 'Magna', 'Sportz', 'Sportz(O)', 'Asta', 'Asta(O)', 'N-Line N6', 'N-Line N8'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.2L Kappa Dual VTVT (1197 cc) / 1.0L Turbo GDi (998 cc)',
    engineOilSpec: '3.4 Litres • 5W-30 / 0W-20 Synthetic',
    coolantSpec: '4.8 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-hyundai-verna',
    make: 'Hyundai',
    model: 'Verna',
    category: 'Sedan',
    variants: ['EX', 'S', 'SX', 'SX(O)', 'SX Turbo', 'SX(O) Turbo DCT'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.5L MPi (1497 cc) / 1.5L Turbo GDi (1482 cc - 160 PS)',
    engineOilSpec: '3.8 Litres • 0W-20 / 5W-30 Synthetic',
    coolantSpec: '5.5 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Sedan with ADAS Level 2 and 7-speed DCT. Inspect DCT clutch calibration during 30k service.',
  },
  {
    id: 'model-hyundai-exter',
    make: 'Hyundai',
    model: 'Exter',
    category: 'Compact SUV',
    variants: ['EX', 'EX(O)', 'S', 'S(O)', 'SX', 'SX(O)', 'SX(O) Connect', 'Hy-CNG Duo S', 'Hy-CNG Duo SX'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L Bi-Fuel Kappa (1197 cc)',
    engineOilSpec: '3.4 Litres • 0W-20 Synthetic',
    coolantSpec: '4.6 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-hyundai-alcazar',
    make: 'Hyundai',
    model: 'Alcazar',
    category: 'SUV',
    variants: ['Prestige', 'Platinum', 'Platinum(O)', 'Signature', 'Signature(O)'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L Turbo GDi (1482 cc) / 1.5L U2 CRDi (1493 cc)',
    engineOilSpec: '4.2L (Petrol) / 4.8L (Diesel) • 5W-30 Synthetic',
    coolantSpec: '6.2 Litres',
    recommendedPsi: '34 PSI (Front) / 36 PSI (Rear)',
  },
  {
    id: 'model-hyundai-tucson',
    make: 'Hyundai',
    model: 'Tucson',
    category: 'Luxury',
    variants: ['Platinum', 'Signature', 'Signature AWD'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L Nu Petrol (1999 cc) / 2.0L R CRDi Diesel (1995 cc - 186 PS)',
    engineOilSpec: '4.5L (Petrol) / 6.2L (Diesel) • 5W-30 Synthetic C3',
    coolantSpec: '7.0 Litres',
    recommendedPsi: '35 PSI (Front) / 35 PSI (Rear)',
  },
  {
    id: 'model-hyundai-ioniq5',
    make: 'Hyundai',
    model: 'Ioniq 5',
    category: 'EV',
    variants: ['Long Range RWD 72.6 kWh'],
    fuelTypes: ['EV'],
    engineDisplacement: 'Permanent Magnet Synchronous Motor (217 PS) • 72.6 kWh Battery',
    engineOilSpec: 'N/A (Electric Reduction Gearbox Oil: 1.2L 75W)',
    coolantSpec: 'Low Conductivity Battery Coolant: 9.5 Litres (Blue Type)',
    recommendedPsi: '36 PSI (Front) / 36 PSI (Rear)',
    notes: '800V Ultra-fast charging EV. Inspect low-conductivity battery coolant and high-voltage cabling insulation.',
  },

  // ==========================================
  // TATA MOTORS
  // ==========================================
  {
    id: 'model-tata-nexon',
    make: 'Tata Motors',
    model: 'Nexon',
    category: 'Compact SUV',
    variants: ['Smart', 'Smart+', 'Pure', 'Pure S', 'Creative', 'Creative+', 'Creative+ S', 'Fearless', 'Fearless+ S', 'iCNG Creative', 'iCNG Fearless'],
    fuelTypes: ['Petrol', 'Diesel', 'CNG'],
    engineDisplacement: '1.2L Revotron Turbo Petrol (1199 cc) / 1.5L Revotorq Diesel (1497 cc)',
    engineOilSpec: '3.5L (Petrol 5W-30) / 4.8L (Diesel 5W-30 C3 Low SAPS)',
    coolantSpec: '5.2 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
    notes: 'Turbo Petrol & Diesel. Check dual-mass flywheel, intercooler hose clamps, and AMT/DCA oil.',
  },
  {
    id: 'model-tata-nexon-ev',
    make: 'Tata Motors',
    model: 'Nexon.ev',
    category: 'EV',
    variants: ['Creative Medium Range', 'Fearless MR', 'Empowered MR', 'Empowered+ Long Range 45kWh', 'Red Dark Edition'],
    fuelTypes: ['EV'],
    engineDisplacement: 'Permanent Magnet AC Motor (145 PS) • 30 kWh MR / 40.5 - 45 kWh LR',
    engineOilSpec: 'Reduction Gear Lubricant: 1.1L 75W-85 GL-4',
    coolantSpec: 'Battery & Power Electronics Coolant: 7.2 Litres',
    recommendedPsi: '34 PSI (Front) / 34 PSI (Rear)',
    isPopular: true,
    notes: 'Best-selling Indian EV. Inspect regenerative braking pads, HV interlock connectors, and CCS2 charging port pin wear.',
  },
  {
    id: 'model-tata-punch',
    make: 'Tata Motors',
    model: 'Punch',
    category: 'Compact SUV',
    variants: ['Pure', 'Adventure', 'Accomplished', 'Accomplished Dazzle', 'Creative', 'Creative Flagship', 'iCNG Adventure', 'iCNG Accomplished'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L Revotron 3-Cyl (1199 cc)',
    engineOilSpec: '3.2 Litres • 5W-30 Synthetic',
    coolantSpec: '4.5 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-tata-punch-ev',
    make: 'Tata Motors',
    model: 'Punch.ev',
    category: 'EV',
    variants: ['Smart', 'Smart+', 'Adventure', 'Empowered', 'Empowered+ Long Range 35kWh'],
    fuelTypes: ['EV'],
    engineDisplacement: 'actitech EV architecture • 25 kWh MR / 35 kWh LR Battery',
    engineOilSpec: 'Gearbox Oil: 1.0L 75W',
    coolantSpec: 'Thermal Management Coolant: 6.0 Litres',
    recommendedPsi: '34 PSI (Front) / 34 PSI (Rear)',
  },
  {
    id: 'model-tata-harrier',
    make: 'Tata Motors',
    model: 'Harrier',
    category: 'SUV',
    variants: ['Smart', 'Smart(O)', 'Pure', 'Pure(O)', 'Adventure', 'Adventure+', 'Fearless', 'Fearless+', 'Dark Edition', 'Stealth'],
    fuelTypes: ['Diesel'],
    engineDisplacement: '2.0L Kryotec Turbocharged Diesel (1956 cc - 170 PS)',
    engineOilSpec: '5.2 Litres • 5W-30 ACEA C2/C3 Low-SAPS',
    coolantSpec: '7.8 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Fiat-derived 2.0L Multijet engine. Inspect SCR AdBlue injector, DPF regeneration status, and Hyundai 6AT transmission fluid.',
  },
  {
    id: 'model-tata-safari',
    make: 'Tata Motors',
    model: 'Safari',
    category: 'SUV',
    variants: ['Smart', 'Pure', 'Adventure', 'Adventure+ Dark', 'Accomplished', 'Accomplished+ 6S', 'Dark Edition'],
    fuelTypes: ['Diesel'],
    engineDisplacement: '2.0L Kryotec Turbocharged Diesel (1956 cc - 170 PS)',
    engineOilSpec: '5.2 Litres • 5W-30 C2/C3 Low-SAPS',
    coolantSpec: '8.2 Litres',
    recommendedPsi: '34 PSI (Front) / 36 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-tata-tiago',
    make: 'Tata Motors',
    model: 'Tiago',
    category: 'Hatchback',
    variants: ['XE', 'XM', 'XT', 'XT(O)', 'XZ', 'XZ Plus', 'iCNG XM', 'iCNG XZ+'],
    fuelTypes: ['Petrol', 'CNG'],
    engineDisplacement: '1.2L Revotron 3-Cyl (1199 cc)',
    engineOilSpec: '3.2 Litres • 5W-30',
    coolantSpec: '4.2 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-tata-tiago-ev',
    make: 'Tata Motors',
    model: 'Tiago.ev',
    category: 'EV',
    variants: ['XE MR 19.2kWh', 'XT MR', 'XT LR 24kWh', 'XZ+ LR', 'XZ+ Tech LUX'],
    fuelTypes: ['EV'],
    engineDisplacement: 'Ziptron High Voltage EV • 19.2 kWh / 24 kWh LFP Battery',
    engineOilSpec: 'Single Speed Reducer Oil: 0.9L',
    coolantSpec: 'Battery Liquid Coolant: 5.5 Litres',
    recommendedPsi: '34 PSI (Front) / 34 PSI (Rear)',
  },

  // ==========================================
  // MAHINDRA
  // ==========================================
  {
    id: 'model-mahindra-scorpio-n',
    make: 'Mahindra',
    model: 'Scorpio-N',
    category: 'SUV',
    variants: ['Z2', 'Z4', 'Z6', 'Z8', 'Z8 Select', 'Z8 L', 'Z8 L 4x4', 'Z8 L AT 4WD'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L mStallion Turbo Petrol (200 PS) / 2.2L mHawk CRDe Diesel (175 PS)',
    engineOilSpec: '6.0 Litres • 5W-30 Maximile FEO / ACEA C3',
    coolantSpec: '8.5 Litres',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
    isPopular: true,
    notes: 'Heavy duty ladder frame chassis. Inspect rear differential fluid, transfer case 4x4 actuator, and brake pad wear.',
  },
  {
    id: 'model-mahindra-xuv700',
    make: 'Mahindra',
    model: 'XUV700',
    category: 'SUV',
    variants: ['MX', 'AX3', 'AX5', 'AX5 Select', 'AX7', 'AX7 L', 'AX7 L AWD', 'Ebony Black Edition'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L mStallion TGDi (200 PS) / 2.2L mHawk CRDe (185 PS)',
    engineOilSpec: '6.0 Litres • 5W-30 Synthetic',
    coolantSpec: '8.8 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Equipped with ADAS radar/camera, electronic flush door handles, and panoramic skyroof. Calibrate ADAS sensors after bumper work.',
  },
  {
    id: 'model-mahindra-thar',
    make: 'Mahindra',
    model: 'Thar / Thar Roxx',
    category: 'SUV',
    variants: ['AX Opt', 'LX Hard Top', 'LX Soft Top', 'Earth Edition', 'Roxx MX1', 'Roxx MX3', 'Roxx AX5L', 'Roxx AX7L 4x4'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L D117 CRDe / 2.0L mStallion / 2.2L mHawk (2184 cc)',
    engineOilSpec: '6.0 Litres • 5W-30 Full Synthetic',
    coolantSpec: '8.0 Litres',
    recommendedPsi: '30 PSI (Front) / 30 PSI (Rear Off-Road/Road)',
    isPopular: true,
    notes: '4WD Off-roader. Regularly inspect front/rear differential breather valves, propeller shaft greasing & steering knuckles.',
  },
  {
    id: 'model-mahindra-xuv3xo',
    make: 'Mahindra',
    model: 'XUV 3XO',
    category: 'Compact SUV',
    variants: ['MX1', 'MX2', 'MX2 Pro', 'MX3', 'MX3 Pro', 'AX5', 'AX5 L', 'AX7', 'AX7 L'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.2L mStallion TCMPFi / 1.2L TGDi (130 PS) / 1.5L Turbo Diesel (117 PS)',
    engineOilSpec: '4.0 Litres • 5W-30 Synthetic',
    coolantSpec: '5.5 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-mahindra-bolero',
    make: 'Mahindra',
    model: 'Bolero / Bolero Neo',
    category: 'SUV',
    variants: ['B4', 'B6', 'B6 Opt', 'Neo N4', 'Neo N8', 'Neo N10', 'Neo N10(O) MLD'],
    fuelTypes: ['Diesel'],
    engineDisplacement: '1.5L mHawk75 / mHawk100 (1493 cc - 100 PS)',
    engineOilSpec: '5.0 Litres • 15W-40 / 5W-30 Maximile',
    coolantSpec: '6.8 Litres',
    recommendedPsi: '32 PSI (Front) / 36 PSI (Rear)',
    isPopular: true,
  },

  // ==========================================
  // TOYOTA
  // ==========================================
  {
    id: 'model-toyota-innova-crysta',
    make: 'Toyota',
    model: 'Innova Crysta',
    category: 'MUV',
    variants: ['GX 7S', 'GX 8S', 'VX 7S', 'VX 8S', 'ZX 7S Luxury', 'Touring Sport'],
    fuelTypes: ['Diesel'],
    engineDisplacement: '2.4L 2GD-FTV D-4D Turbo Diesel (2393 cc - 150 PS)',
    engineOilSpec: '6.5 Litres • 5W-30 Toyota Genuine Motor Oil C2',
    coolantSpec: '8.6 Litres • Toyota Super Long Life Coolant (Pink)',
    recommendedPsi: '33 PSI (Front) / 35 PSI (Rear)',
    isPopular: true,
    notes: 'Legendary reliability. Inspect propeller shaft center bearing, intercooler rubber couplers, and front disc brake pads.',
  },
  {
    id: 'model-toyota-innova-hycross',
    make: 'Toyota',
    model: 'Innova Hycross',
    category: 'MUV',
    variants: ['GX (Petrol)', 'GX(O) (Petrol)', 'VX Hybrid', 'VX(O) Hybrid', 'ZX Hybrid', 'ZX(O) Hybrid OTTOMAN'],
    fuelTypes: ['Petrol', 'Hybrid'],
    engineDisplacement: '2.0L M20A-FKS Dynamic Force (1987 cc) / 2.0L 5th Gen Self-Charging Strong Hybrid',
    engineOilSpec: '4.2 Litres • 0W-16 / 0W-20 Full Synthetic',
    coolantSpec: '6.8 Litres (Engine) + 2.1 Litres (Inverter Cooling)',
    recommendedPsi: '34 PSI (Front) / 34 PSI (Rear)',
    isPopular: true,
    notes: 'TNGA-C Monocoque Chassis with e-CVT and Ottoman lounge seats. Inspect regenerative braking components.',
  },
  {
    id: 'model-toyota-fortuner',
    make: 'Toyota',
    model: 'Fortuner',
    category: 'SUV',
    variants: ['4x2 MT Petrol', '4x2 AT Petrol', '4x2 MT Diesel', '4x2 AT Diesel', '4x4 MT Diesel', '4x4 AT Diesel', 'Legender 4x2', 'Legender 4x4', 'GR-Sport 4x4'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.7L 2TR-FE Petrol (166 PS) / 2.8L 1GD-FTV Diesel (204 PS - 500 Nm)',
    engineOilSpec: '7.5 Litres Diesel • 5W-30 Low-SAPS / 5.5 Litres Petrol',
    coolantSpec: '9.2 Litres (Pink SLLC)',
    recommendedPsi: '30 PSI (Front) / 30 PSI (Rear Comfort)',
    isPopular: true,
    notes: 'Heavy ladder-frame 4WD. Replace transfer case gear oil & differential fluid every 40,000 km.',
  },
  {
    id: 'model-toyota-hyryder',
    make: 'Toyota',
    model: 'Urban Cruiser Hyryder',
    category: 'SUV',
    variants: ['E (NeoDrive)', 'S (NeoDrive)', 'G (NeoDrive)', 'V (NeoDrive)', 'V AWD', 'S CNG', 'G CNG', 'G Strong Hybrid', 'V Strong Hybrid'],
    fuelTypes: ['Petrol', 'CNG', 'Hybrid'],
    engineDisplacement: '1.5L K15C (103 PS) / 1.5L 3-Cyl M15D Strong Hybrid (116 PS)',
    engineOilSpec: '3.6 Litres • 0W-16 Synthetic',
    coolantSpec: '5.5 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-toyota-camry',
    make: 'Toyota',
    model: 'Camry',
    category: 'Luxury',
    variants: ['2.5 Dynamic Force Hybrid Luxury'],
    fuelTypes: ['Hybrid'],
    engineDisplacement: '2.5L 4-Cyl A25A-FXS Hybrid (218 PS Combined)',
    engineOilSpec: '4.5 Litres • 0W-16 Full Synthetic',
    coolantSpec: '6.5 Litres Engine + 1.8 Litres Inverter',
    recommendedPsi: '32 PSI (Front) / 32 PSI (Rear)',
  },

  // ==========================================
  // HONDA
  // ==========================================
  {
    id: 'model-honda-city',
    make: 'Honda',
    model: 'City',
    category: 'Sedan',
    variants: ['SV MT', 'V MT', 'V CVT', 'VX MT', 'VX CVT', 'ZX MT', 'ZX CVT', 'e:HEV Hybrid V', 'e:HEV Hybrid ZX', 'Elegant Edition'],
    fuelTypes: ['Petrol', 'Hybrid'],
    engineDisplacement: '1.5L i-VTEC DOHC (1498 cc - 121 PS) / 1.5L Atkinson Cycle Dual-Motor e:HEV (126 PS)',
    engineOilSpec: '3.6 Litres • 0W-20 / 5W-30 Honda Genuine Synthetic Oil',
    coolantSpec: '4.8 Litres • Honda Type 2 All-Season Coolant',
    recommendedPsi: '32 PSI (Front) / 30 PSI (Rear)',
    isPopular: true,
    notes: 'Iconic executive sedan. Check CVT transmission fluid condition every 40k km. Inspect lower control arm bushes.',
  },
  {
    id: 'model-honda-elevate',
    make: 'Honda',
    model: 'Elevate',
    category: 'SUV',
    variants: ['SV MT', 'V MT', 'V CVT', 'VX MT', 'VX CVT', 'ZX MT', 'ZX CVT', 'Black Edition', 'Apex Edition'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.5L i-VTEC DOHC (1498 cc - 121 PS)',
    engineOilSpec: '3.6 Litres • 0W-20 Synthetic',
    coolantSpec: '5.2 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-honda-amaze',
    make: 'Honda',
    model: 'Amaze',
    category: 'Sedan',
    variants: ['E', 'S MT', 'S CVT', 'VX MT', 'VX CVT', 'Elite Edition'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.2L i-VTEC 4-Cyl (1199 cc - 90 PS)',
    engineOilSpec: '3.2 Litres • 0W-20 Synthetic',
    coolantSpec: '4.0 Litres',
    recommendedPsi: '32 PSI (Front) / 30 PSI (Rear)',
    isPopular: true,
  },

  // ==========================================
  // KIA
  // ==========================================
  {
    id: 'model-kia-seltos',
    make: 'Kia',
    model: 'Seltos',
    category: 'SUV',
    variants: ['HTE', 'HTK', 'HTK+', 'HTX', 'HTX+', 'GTX+', 'GTX+ S', 'X-Line', 'X-Line Turbo', 'Gravity Edition'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L Smartstream MPi (115 PS) / 1.5L Turbo GDi (160 PS) / 1.5L CRDi VGT (116 PS)',
    engineOilSpec: '3.8L Petrol / 4.8L Diesel • 5W-30 Synthetic C3',
    coolantSpec: '5.8 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'Mid-size SUV with DCT/AT/iMT options. Check brake pad life, panoramic sunroof drainage channels, and DPF saturation.',
  },
  {
    id: 'model-kia-sonet',
    make: 'Kia',
    model: 'Sonet',
    category: 'Compact SUV',
    variants: ['HTE', 'HTK', 'HTK(O)', 'HTK+', 'HTX', 'HTX+', 'GTX+', 'X-Line'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.2L Smartstream / 1.0L Turbo GDi (120 PS) / 1.5L CRDi VGT (116 PS)',
    engineOilSpec: '3.4L (1.2L) / 3.6L (1.0L) / 4.5L (Diesel) • 5W-30',
    coolantSpec: '5.0 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-kia-carens',
    make: 'Kia',
    model: 'Carens',
    category: 'MUV',
    variants: ['Premium', 'Prestige', 'Prestige Plus', 'Prestige+ (O)', 'Luxury', 'Luxury Plus', 'X-Line'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L Smartstream / 1.5L Turbo GDi (160 PS) / 1.5L CRDi VGT (116 PS)',
    engineOilSpec: '4.0L (Petrol) / 4.8L (Diesel) • 5W-30 Synthetic',
    coolantSpec: '6.0 Litres',
    recommendedPsi: '34 PSI (Front) / 36 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-kia-ev6',
    make: 'Kia',
    model: 'EV6',
    category: 'EV',
    variants: ['GT-Line RWD 77.4 kWh', 'GT-Line AWD Dual Motor (325 PS)'],
    fuelTypes: ['EV'],
    engineDisplacement: 'E-GMP Dedicated EV Platform • 77.4 kWh Battery (325 PS / 605 Nm)',
    engineOilSpec: 'Dual Motor Reduction Gear Fluid: 2.2 Litres',
    coolantSpec: 'Dual Circuit Battery Thermal Fluid: 10.5 Litres',
    recommendedPsi: '36 PSI (Front) / 36 PSI (Rear)',
  },

  // ==========================================
  // VOLKSWAGEN & SKODA
  // ==========================================
  {
    id: 'model-vw-virtus',
    make: 'Volkswagen',
    model: 'Virtus',
    category: 'Sedan',
    variants: ['Comfortline 1.0', 'Highline 1.0 MT/AT', 'Topline 1.0 MT/AT', 'GT 1.5 DSG', 'GT Plus 1.5 DSG/MT', 'GT Edge Carbon Steel Matte'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.0L TSI (999 cc - 115 PS) / 1.5L TSI EVO Active Cylinder Tech (1498 cc - 150 PS)',
    engineOilSpec: '3.6L (1.0L) / 4.0L (1.5L) • 0W-20 / 5W-30 VW 504.00 / 508.00 LongLife',
    coolantSpec: '5.6 Litres • G12evo / G13 Pink Coolant',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
    notes: 'MQB-A0-IN Sedan. Use VW certified 504.00/508.00 spec oil. Inspect DQ200 7-speed DSG mechatronic operation.',
  },
  {
    id: 'model-vw-taigun',
    make: 'Volkswagen',
    model: 'Taigun',
    category: 'Compact SUV',
    variants: ['Comfortline', 'Highline', 'Topline', 'GT', 'GT Plus DSG', 'GT Edge Trail'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.0L TSI (115 PS) / 1.5L TSI EVO (150 PS - 250 Nm)',
    engineOilSpec: '3.6L (1.0L) / 4.0L (1.5L) • VW 504.00 / 508.00 Full Synthetic',
    coolantSpec: '5.6 Litres • G12evo Pink',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-skoda-slavia',
    make: 'Skoda',
    model: 'Slavia',
    category: 'Sedan',
    variants: ['Classic 1.0', 'Signature 1.0', 'Prestige 1.0', 'Sportline 1.0/1.5', 'Monte Carlo 1.5 DSG', 'Elegance Edition'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.0L TSI (115 PS) / 1.5L TSI EVO (150 PS)',
    engineOilSpec: '3.6L (1.0 TSI) / 4.0L (1.5 TSI) • VW 508.00 0W-20',
    coolantSpec: '5.6 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-skoda-kushaq',
    make: 'Skoda',
    model: 'Kushaq',
    category: 'Compact SUV',
    variants: ['Classic', 'Signature', 'Prestige', 'Onyx Edition', 'Monte Carlo 1.0/1.5', 'Elegance Edition'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '1.0L TSI (115 PS) / 1.5L TSI EVO (150 PS)',
    engineOilSpec: '3.6L (1.0L) / 4.0L (1.5L) • VW 508.00 Synthetic',
    coolantSpec: '5.6 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },

  // ==========================================
  // MG MOTOR
  // ==========================================
  {
    id: 'model-mg-hector',
    make: 'MG Motor',
    model: 'Hector / Hector Plus',
    category: 'SUV',
    variants: ['Style', 'Shine Pro', 'Select Pro', 'Smart Pro', 'Sharp Pro', 'Savvy Pro ADAS', 'Blackstorm'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L Turbo Petrol (143 PS) / 2.0L Multijet Turbo Diesel (170 PS)',
    engineOilSpec: '4.2L (Petrol) / 5.2L (Diesel) • 5W-30 Synthetic',
    coolantSpec: '7.2 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
  {
    id: 'model-mg-zs-ev',
    make: 'MG Motor',
    model: 'ZS EV',
    category: 'EV',
    variants: ['Executive 50.3kWh', 'Excite Pro', 'Exclusive Plus', 'Essence 50.3 kWh'],
    fuelTypes: ['EV'],
    engineDisplacement: 'Permanent Magnet Motor (176 PS - 280 Nm) • 50.3 kWh Prismatic Cell Battery',
    engineOilSpec: 'E-Drive Transmission Oil: 1.2L',
    coolantSpec: 'Battery High Voltage Cooling Fluid: 6.8 Litres',
    recommendedPsi: '36 PSI (Front) / 36 PSI (Rear)',
  },

  // ==========================================
  // GERMAN LUXURY (BMW, MERCEDES-BENZ, AUDI)
  // ==========================================
  {
    id: 'model-bmw-3-series',
    make: 'BMW',
    model: '3 Series Gran Limousine',
    category: 'Luxury',
    variants: ['330Li M Sport', '320Ld M Sport', '330Li Luxury Line', 'M340i xDrive 3.0L B58'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L B48 TwinPower Turbo (258 PS) / 2.0L B47 Diesel (190 PS) / 3.0L B58 Inline-6 (374 PS)',
    engineOilSpec: '5.25L (2.0L B48) / 5.5L (B47 Diesel) / 6.5L (M340i) • BMW Longlife-04 5W-30 / 0W-30',
    coolantSpec: '7.5 Litres • BMW Coolant (Blue-Green / Magenta HT-12)',
    recommendedPsi: '32 PSI (Front) / 35 PSI (Rear)',
    isPopular: true,
    notes: 'Luxury sports sedan. Requires BMW ISTA diagnostic scan for CBS (Condition Based Service) reset. Inspect run-flat tire wear.',
  },
  {
    id: 'model-bmw-5-series',
    make: 'BMW',
    model: '5 Series',
    category: 'Luxury',
    variants: ['530Li M Sport LWB', '520d Luxury Line', '530i M Sport', '530d M Sport 3.0L'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L 48V Mild Hybrid B48 (258 PS) / 2.0L B47 Diesel / 3.0L B57 Straight-6',
    engineOilSpec: '5.5 Litres • BMW Longlife-04 / LL-12 FE Synthetic',
    coolantSpec: '8.2 Litres',
    recommendedPsi: '34 PSI (Front) / 38 PSI (Rear)',
  },
  {
    id: 'model-bmw-x1',
    make: 'BMW',
    model: 'X1 / iX1',
    category: 'Luxury',
    variants: ['sDrive18i xLine', 'sDrive18d M Sport', 'iX1 xDrive30 EV 66.4 kWh'],
    fuelTypes: ['Petrol', 'Diesel', 'EV'],
    engineDisplacement: '1.5L 3-Cyl Turbo (136 PS) / 2.0L Diesel (150 PS) / Dual Electric Motors (313 PS)',
    engineOilSpec: '4.5L • BMW Longlife-04 5W-30',
    coolantSpec: '6.5 Litres',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
  },
  {
    id: 'model-mercedes-c-class',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    category: 'Luxury',
    variants: ['C 200', 'C 220 d', 'C 300 d AMG Line', 'C 300 Night Edition'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '1.5L M254 Turbo with EQ Boost (204 PS) / 2.0L OM654M Diesel (265 PS - 550 Nm)',
    engineOilSpec: '6.0L (Petrol) / 6.8L (Diesel) • MB Approval 229.51 / 229.52 Full Synthetic',
    coolantSpec: '8.0 Litres • MB 325.6 / 326.6 Coolant',
    recommendedPsi: '34 PSI (Front) / 38 PSI (Rear)',
    isPopular: true,
    notes: 'MBUX digital cockpit & 9G-TRONIC. Reset Assyst Plus service indicator. Inspect multi-link front suspension bushes.',
  },
  {
    id: 'model-mercedes-e-class',
    make: 'Mercedes-Benz',
    model: 'E-Class LWB',
    category: 'Luxury',
    variants: ['E 200 Exclusive', 'E 220 d Expression', 'E 220 d Exclusive', 'E 450 4MATIC AMG Line 6-Cyl'],
    fuelTypes: ['Petrol', 'Diesel'],
    engineDisplacement: '2.0L M254 (204 PS) / 2.0L OM654M (197 PS) / 3.0L M256 Inline-6 (381 PS)',
    engineOilSpec: '6.5L • MB 229.52 Synthetic',
    coolantSpec: '9.0 Litres',
    recommendedPsi: '35 PSI (Front) / 39 PSI (Rear)',
  },
  {
    id: 'model-audi-a4',
    make: 'Audi',
    model: 'A4',
    category: 'Luxury',
    variants: ['Premium 40 TFSI', 'Premium Plus 40 TFSI', 'Technology 40 TFSI'],
    fuelTypes: ['Petrol'],
    engineDisplacement: '2.0L 40 TFSI Turbocharged (1984 cc - 204 PS / 320 Nm)',
    engineOilSpec: '5.2 Litres • VW 504.00 / 508.00 LongLife III 0W-20',
    coolantSpec: '7.2 Litres • G13 / G12evo Violet',
    recommendedPsi: '33 PSI (Front) / 33 PSI (Rear)',
    isPopular: true,
  },
];
