import { 
  Employee, Vendor, JobCard, StandardServicePackage, PurchaseOrder, 
  DeliveryRecord, CityServiceOffering, ServiceBookingRequest, InventoryItem, 
  StandardJob, VehicleCheckIn, Workshop 
} from '../types';

export const INITIAL_CITY_SERVICES: CityServiceOffering[] = [
  {
    id: 'srv-periodic-30',
    title: 'Comprehensive Periodic Service',
    category: 'MECHANICAL',
    tagline: 'Complete 30-Point Check, Synthetic Engine Oil, Oil & Air Filter Replacement, OBD-II Scan',
    description: 'Full periodic engine tune-up with synthetic oil flush, spark plug checks, brake pad wear inspection, coolant top-up, and eco steam wash.',
    estimatedHours: 3.5,
    isPopular: true,
    cityPrices: {
      'Mumbai': 3499,
      'Delhi NCR': 2999,
      'Bengaluru': 3299,
      'Hyderabad': 2899,
      'Pune': 2999,
      'Chennai': 2899,
      'Jaipur': 2499,
      'Ahmedabad': 2599,
      'Chandigarh': 2699,
      'Kolkata': 2799,
    },
    includedFeatures: [
      'Synthetic Engine Oil (up to 4L) & Filter Replacement',
      'Cabin Air Filter & Fuel Line Cleaning',
      '30-Point Computerized OBD-II Diagnostics Scan',
      'Brake Pad & Rotor Thickness Check',
      'Coolant, Brake Fluid & Battery Top-Up',
      'Complimentary Interior Vacuum & Eco Steam Wash'
    ]
  },
  {
    id: 'srv-ac-chilling',
    title: 'AC Deep Chilling & Gas Refill',
    category: 'MECHANICAL',
    tagline: 'High-grade R134a Gas Recharge, Condenser Cleaning, Leak Test & Antibacterial Treatment',
    description: 'Beat the heat with full AC system diagnostics, vacuum leak testing, condenser pressure wash, and fresh R134a gas recharge.',
    estimatedHours: 2,
    isPopular: true,
    cityPrices: {
      'Mumbai': 2499,
      'Delhi NCR': 2199,
      'Bengaluru': 2299,
      'Hyderabad': 1999,
      'Pune': 2099,
      'Chennai': 2199,
      'Jaipur': 1899,
      'Ahmedabad': 1999,
      'Chandigarh': 1999,
      'Kolkata': 2099,
    },
    includedFeatures: [
      'Environment Friendly R134a Gas Top-Up',
      'Compressor Oil & Leakage Vacuum Testing',
      'Condenser & Cooling Coil Pressure Wash',
      'AC Vent Antibacterial Foam Cleaning',
      'Cabin AC Dust Filter Cleaning / Replacement Check'
    ]
  },
  {
    id: 'srv-brake-alignment',
    title: 'Brake Overhaul & 3D Wheel Alignment',
    category: 'MECHANICAL',
    tagline: 'Front & Rear Brake Pad Renewal, Rotor Lathe Resurfacing & 3D Laser Alignment',
    description: 'Ensure maximum stopping safety and smooth steering stability with precision brake overhaul and 3D laser alignment.',
    estimatedHours: 3,
    isPopular: false,
    cityPrices: {
      'Mumbai': 4299,
      'Delhi NCR': 3899,
      'Bengaluru': 3999,
      'Hyderabad': 3699,
      'Pune': 3799,
      'Chennai': 3599,
      'Jaipur': 3299,
      'Ahmedabad': 3399,
      'Chandigarh': 3499,
      'Kolkata': 3499,
    },
    includedFeatures: [
      'Front Ceramic Brake Pad Replacement',
      'Brake Disc Rotor Skimming & Lathe Resurfacing',
      'Brake Fluid Bleeding & Flushing (DOT 4)',
      'Computerized 3D Laser Wheel Alignment',
      '4-Wheel Dynamic Balancing & Tire Rotation'
    ]
  },
  {
    id: 'srv-denting-painting',
    title: 'Panel Denting & Paint Restoration',
    category: 'PAINT',
    tagline: 'Precision Metal Pulling, Anti-Rust Primer & Heated Booth Metallic Painting',
    description: 'Flawless panel paint restoration using computerized color matching, anti-corrosion primer, and clear coat baking.',
    estimatedHours: 6,
    isPopular: true,
    cityPrices: {
      'Mumbai': 3200,
      'Delhi NCR': 2800,
      'Bengaluru': 2999,
      'Hyderabad': 2600,
      'Pune': 2700,
      'Chennai': 2600,
      'Jaipur': 2400,
      'Ahmedabad': 2500,
      'Chandigarh': 2500,
      'Kolkata': 2600,
    },
    includedFeatures: [
      'Panel Dent Pulling & Surface Leveling',
      'Anti-Rust Epoxy Primer Coat',
      '3-Layer High Temperature Baked Metallic Paint',
      '3M Buffing, Polishing & Clear Coat Sealant',
      '2-Year Paint Color Protection Warranty'
    ]
  },
  {
    id: 'srv-interior-detailing',
    title: 'Full Interior Spa & Ceramic Polishing',
    category: 'WASHING',
    tagline: 'Deep Upholstery Steam Wash, Dashboard Protection & Exterior Ceramic Shield',
    description: 'Transform your vehicle inside and out with deep interior foam extraction and hydrophobic paint ceramic polish.',
    estimatedHours: 4,
    isPopular: false,
    cityPrices: {
      'Mumbai': 3999,
      'Delhi NCR': 3499,
      'Bengaluru': 3699,
      'Hyderabad': 3299,
      'Pune': 3399,
      'Chennai': 3299,
      'Jaipur': 2999,
      'Ahmedabad': 3099,
      'Chandigarh': 3199,
      'Kolkata': 3199,
    },
    includedFeatures: [
      'Hot Steam Interior Upholstery Wash & Stain Removal',
      'Dashboard & Leather Trim UV Conditioning',
      'Ozone Sanitization & Odor Eliminator',
      'High-Gloss Paint Buffing & Ceramic Paste Wax',
      'Engine Bay Detailing & Rubber Dressing'
    ]
  },
  {
    id: 'srv-clutch-transmission',
    title: 'Clutch Assembly Overhaul',
    category: 'MECHANICAL',
    tagline: 'Clutch Plate & Pressure Plate Renewal, Release Bearing & Gear Oil Flush',
    description: 'Eliminate clutch slippage, harsh gear shifts, and poor pickup with genuine OEM clutch replacement.',
    estimatedHours: 5,
    isPopular: false,
    cityPrices: {
      'Mumbai': 8499,
      'Delhi NCR': 7499,
      'Bengaluru': 7999,
      'Hyderabad': 7299,
      'Pune': 7399,
      'Chennai': 7199,
      'Jaipur': 6899,
      'Ahmedabad': 6999,
      'Chandigarh': 7099,
      'Kolkata': 7199,
    },
    includedFeatures: [
      'OEM Clutch Plate & Pressure Plate Replacement',
      'Clutch Release Bearing Installation',
      'Flywheel Facing & Alignment Check',
      'Synthetic Gearbox Oil Flush & Refill',
      'Clutch Cable / Hydraulic Cylinder Bleeding'
    ]
  }
];

export const INITIAL_SERVICE_BOOKINGS: ServiceBookingRequest[] = [];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-admin',
    name: 'Super Admin',
    role: 'SUPER_ADMIN',
    phone: '',
    email: 'admin@fixocar.com',
    loginId: 'admin',
    password: 'password123',
    specializedTeam: 'Management',
    status: 'AVAILABLE',
    activeJobsCount: 0,
    employmentType: 'PAYROLL',
  }
];

export const INITIAL_VENDORS: Vendor[] = [];

export const INITIAL_WORKSHOPS: Workshop[] = [];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [];

export const INITIAL_STANDARD_JOBS: StandardJob[] = [
  {
    id: 'std-bumper-front-full',
    title: 'Front Bumper (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'bumper_front',
    panelNameEn: 'Front Bumper',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1050,
    retailDenterPayout: 200,
    retailContractorPayout: 1250,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1250,
    painterPayout: 1050,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Front bumper dismounting, plastic primer, metallic color match & baked clear coat.'
  },
  {
    id: 'std-hood-bonnet-full',
    title: 'Hood / Bonnet (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'hood_bonnet',
    panelNameEn: 'Hood / Bonnet',
    paintScope: 'FULL_OUTER',
    retailPrice: 2200,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1150,
    retailDenterPayout: 250,
    retailContractorPayout: 1400,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1400,
    painterPayout: 1150,
    denterPayout: 250,
    estimatedHours: 4,
    description: 'Bonnet surface dent leveling, high-temperature heat coat and premium clear lacquer finish.'
  },
  {
    id: 'std-fender-lhs-full',
    title: 'Left Front Fender (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'fender_lhs',
    panelNameEn: 'Left Front Fender',
    paintScope: 'FULL_OUTER',
    retailPrice: 1600,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 850,
    retailDenterPayout: 180,
    retailContractorPayout: 1030,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1030,
    painterPayout: 850,
    denterPayout: 180,
    estimatedHours: 3,
    description: 'Front left fender dent pulling, surface anti-rust primer coat, and metallic paint.'
  },
  {
    id: 'std-fender-rhs-full',
    title: 'Right Front Fender (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'fender_rhs',
    panelNameEn: 'Right Front Fender',
    paintScope: 'FULL_OUTER',
    retailPrice: 1600,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 850,
    retailDenterPayout: 180,
    retailContractorPayout: 1030,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1030,
    painterPayout: 850,
    denterPayout: 180,
    estimatedHours: 3,
    description: 'Front right fender dent pulling, surface anti-rust primer coat, and metallic paint.'
  },
  {
    id: 'std-roof-full',
    title: 'Roof Panel (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'roof',
    panelNameEn: 'Roof Panel',
    paintScope: 'FULL_OUTER',
    retailPrice: 3200,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1700,
    retailDenterPayout: 350,
    retailContractorPayout: 2050,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 2050,
    painterPayout: 1700,
    denterPayout: 350,
    estimatedHours: 5,
    description: 'Full roof surface sanding, anti-corrosion base coat, and high-gloss 2K clear lacquer.'
  },
  {
    id: 'std-door-lhs-front-full',
    title: 'Door LHS Front (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_lhs_front',
    panelNameEn: 'Door LHS Front',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1150,
    painterPayout: 950,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Left front door panel metal dent pulling, color blend, and baked clear coat.'
  },
  {
    id: 'std-door-lhs-rear-full',
    title: 'Door LHS Rear (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_lhs_rear',
    panelNameEn: 'Door LHS Rear',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1150,
    painterPayout: 950,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Left rear door panel metal dent pulling, color blend, and baked clear coat.'
  },
  {
    id: 'std-running-board-lhs-full',
    title: 'Running Board LHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'running_board_lhs',
    panelNameEn: 'Running Board LHS (Sill)',
    paintScope: 'FULL_OUTER',
    retailPrice: 1200,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 650,
    retailDenterPayout: 150,
    retailContractorPayout: 800,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 800,
    painterPayout: 650,
    denterPayout: 150,
    estimatedHours: 2.5,
    description: 'Left running board sill dent straightening, stone-guard primer and matching paint.'
  },
  {
    id: 'std-quarter-panel-lhs-full',
    title: 'Quarter Panel LHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'quarter_panel_lhs',
    panelNameEn: 'Quarter Panel LHS',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1050,
    retailDenterPayout: 220,
    retailContractorPayout: 1270,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1270,
    painterPayout: 1050,
    denterPayout: 220,
    estimatedHours: 4,
    description: 'Rear left quarter panel metal pulling, seamless C-pillar paint blending and clear lacquer.'
  },
  {
    id: 'std-door-rhs-front-full',
    title: 'Door RHS Front (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_rhs_front',
    panelNameEn: 'Door RHS Front',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1150,
    painterPayout: 950,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Right front door panel metal dent pulling, color match and baked clear coat.'
  },
  {
    id: 'std-door-rhs-rear-full',
    title: 'Door RHS Rear (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_rhs_rear',
    panelNameEn: 'Door RHS Rear',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1150,
    painterPayout: 950,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Right rear door panel metal dent pulling, color match and baked clear coat.'
  },
  {
    id: 'std-running-board-rhs-full',
    title: 'Running Board RHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'running_board_rhs',
    panelNameEn: 'Running Board RHS (Sill)',
    paintScope: 'FULL_OUTER',
    retailPrice: 1200,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 650,
    retailDenterPayout: 150,
    retailContractorPayout: 800,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 800,
    painterPayout: 650,
    denterPayout: 150,
    estimatedHours: 2.5,
    description: 'Right running board sill dent straightening, stone-guard primer and matching paint.'
  },
  {
    id: 'std-quarter-panel-rhs-full',
    title: 'Quarter Panel RHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'quarter_panel_rhs',
    panelNameEn: 'Quarter Panel RHS',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1050,
    retailDenterPayout: 220,
    retailContractorPayout: 1270,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1270,
    painterPayout: 1050,
    denterPayout: 220,
    estimatedHours: 4,
    description: 'Rear right quarter panel metal pulling, seamless C-pillar paint blending and clear lacquer.'
  },
  {
    id: 'std-boot-trunk-full',
    title: 'Boot Lid / Tailgate (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'boot_trunk',
    panelNameEn: 'Boot Lid / Tailgate',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1050,
    retailDenterPayout: 220,
    retailContractorPayout: 1270,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1270,
    painterPayout: 1050,
    denterPayout: 220,
    estimatedHours: 3.5,
    description: 'Boot lid / tailgate surface dent straightening, anti-rust primer & glossy finish.'
  },
  {
    id: 'std-bumper-rear-full',
    title: 'Rear Bumper (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'bumper_rear',
    panelNameEn: 'Rear Bumper',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 1050,
    retailDenterPayout: 200,
    retailContractorPayout: 1250,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 1250,
    painterPayout: 1050,
    denterPayout: 200,
    estimatedHours: 3.5,
    description: 'Rear bumper dismounting, plastic primer, metallic color match & baked clear coat.'
  },
  {
    id: 'std-boot-floor-full',
    title: 'Trunk Floor / Underbody Paint',
    category: 'PAINT',
    panelKey: 'boot_floor',
    panelNameEn: 'Trunk Floor / Underbody',
    paintScope: 'FULL_OUTER',
    retailPrice: 1000,
    cars24Price: 1350,
    isContractBasis: true,
    retailPainterPayout: 500,
    retailDenterPayout: 100,
    retailContractorPayout: 600,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 600,
    painterPayout: 500,
    denterPayout: 100,
    estimatedHours: 2,
    description: 'Trunk spare tire cavity & underbody anti-rust rubberized coating.'
  },
  {
    id: 'std-foam-wash-vacuum',
    title: 'Full Body Foam Wash & Interior Vacuuming',
    category: 'WASHING',
    retailPrice: 600,
    cars24Price: 400,
    isContractBasis: false,
    retailContractorPayout: 150,
    cars24ContractorPayout: 100,
    contractorPayout: 150,
    estimatedHours: 1,
    description: 'Complete exterior foam pressure wash, underbody jet spray, tire dressing and interior cabin vacuuming.'
  },
  {
    id: 'std-periodic-service',
    title: 'Periodic General Service Package',
    category: 'SERVICE',
    retailPrice: 2800,
    cars24Price: 2000,
    isContractBasis: false,
    retailContractorPayout: 400,
    cars24ContractorPayout: 300,
    contractorPayout: 400,
    estimatedHours: 2.5,
    description: 'Engine oil & filter change, air filter cleaning, coolant top-up & 40-point vehicle checkup.'
  },
  {
    id: 'std-front-brake-pads',
    title: 'Front Brake Pads Replacement',
    category: 'MECHANICAL',
    retailPrice: 1400,
    cars24Price: 1000,
    isContractBasis: false,
    retailContractorPayout: 250,
    cars24ContractorPayout: 180,
    contractorPayout: 250,
    estimatedHours: 1.5,
    description: 'Brake pad removal, rotor inspection, caliper greasing and new pad fitment.'
  }
];

export const STANDARD_PACKAGES: StandardServicePackage[] = [
  {
    id: 'pkg-full-service',
    name: 'Comprehensive Periodic Service (30-Point)',
    tagline: 'Complete mechanical tune-up, fluid replacement & 30-point safety check',
    basePrice: 3499,
    estimatedHours: 4,
    includedTasks: [
      { title: 'Engine Oil & Filter Replacement (Synthetic 5W-30)', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 1200, price: 1850 },
      { title: 'Air Filter & Cabin AC Filter Replacement', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 350, price: 650 },
      { title: 'Brake Pad & Rotor Wear Thickness Inspection', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 200, price: 400 },
      { title: 'Spark Plug & Ignition Coil Test', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 300, price: 500 },
      { title: 'Coolant & Transmission Fluid Top-up', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 250, price: 450 },
      { title: '30-Point Computerized OBD-II Diagnostics Scan', category: 'INSPECTION', defaultTeam: 'Management', estimatedCost: 300, price: 600 },
      { title: 'Eco Steam Wash & Interior Vacuuming (Sublet)', category: 'WASHING', defaultTeam: 'Detailing & Washing', estimatedCost: 250, price: 500 },
    ]
  },
  {
    id: 'pkg-brake-suspension',
    name: 'Brake Overhaul & Suspension Alignment',
    tagline: 'Front & Rear brake pad renewal, rotor resurfacing and 3D wheel alignment',
    basePrice: 4299,
    estimatedHours: 5,
    includedTasks: [
      { title: 'Front Ceramic Brake Pad Replacement', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 1400, price: 2200 },
      { title: 'Brake Disc Lathe Resurfacing (Sublet Lathe)', category: 'SUBLET_VENDOR', defaultTeam: 'Sublet / Lathe', estimatedCost: 600, price: 1100 },
      { title: 'Brake Fluid Flushing & Bleeding (DOT 4)', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 300, price: 600 },
      { title: 'Suspension Bushing & Strut Inspection', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 200, price: 450 },
      { title: '3D Laser Wheel Alignment & Balancing', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 400, price: 850 },
    ]
  },
  {
    id: 'pkg-body-paint',
    name: 'Denting & Panel Paint Restoration',
    tagline: 'Precision metal pulling, primer coat & booth baked ceramic lacquer paint',
    basePrice: 3200,
    estimatedHours: 8,
    includedTasks: [
      { title: 'Panel Dent Pulling & Surface Leveling', category: 'DENTING', defaultTeam: 'Denting', estimatedCost: 800, price: 1500 },
      { title: 'Anti-Rust Epoxy Primer Application', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 400, price: 800 },
      { title: 'High-Temperature Baked Metallic Paint & Clear Coat', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 1200, price: 2200 },
      { title: '3M Buffing, Polishing & Paint Protection Sealant', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 300, price: 700 },
    ]
  }
];

export const INITIAL_DELIVERIES: DeliveryRecord[] = [];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [];

export const INITIAL_JOB_CARDS: JobCard[] = [
  {
    id: 'JC-2026-101',
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    estimatedCompletionDate: new Date(Date.now() + 3600000 * 24).toISOString(),
    isUrgent: true,
    isCars24: true,
    cars24RefNo: 'C24-MUM-8821',
    vehicle: {
      registrationNumber: 'MH02CB9988',
      make: 'Maruti Suzuki',
      model: 'Swift VXi',
      year: 2022,
      color: 'Arctic White',
      vin: 'MA3FNE11S0029381',
      fuelLevel: 65,
      mileage: 34500
    },
    customer: {
      id: 'cust-101',
      name: 'Cars24 Hub - Andheri West',
      phone: '+91 98200 11223',
      email: 'hub.andheri@cars24.com',
      address: 'Plot 14, MIDC Industrial Area, Andheri West, Mumbai'
    },
    status: 'IN_PROGRESS',
    serviceType: 'ACCIDENT_BODYWORK',
    packageName: 'Cars24 Panel Denting & Paint Refinishing',
    floorManagerId: 'emp-101',
    floorManagerName: 'Rajesh Sharma (Floor Manager)',
    cityName: 'Mumbai',
    workshopName: 'FixoCar Central Workshop - Andheri',
    tasks: [
      {
        id: 'task-101-1',
        jobCardId: 'JC-2026-101',
        title: 'Bonnet Panel Hydraulic Dent Leveling',
        category: 'DENTING',
        assignedToId: 'emp-104',
        assignedToName: 'David O\'Connor (Denter)',
        assignedType: 'EMPLOYEE',
        estimatedCost: 350,
        customerPrice: 600,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        completedAt: new Date(Date.now() - 3600000 * 12).toISOString(),
        notes: 'Hydraulic pull completed, primer ready.'
      },
      {
        id: 'task-101-2',
        jobCardId: 'JC-2026-101',
        title: 'Bonnet 2K Baked Clear Paint Refinish',
        category: 'PAINT',
        assignedToId: 'emp-105',
        assignedToName: 'Kenji Sato (Painter)',
        assignedType: 'EMPLOYEE',
        estimatedCost: 800,
        customerPrice: 1350,
        status: 'IN_PROGRESS',
        requiresCustomerApproval: false,
        notes: 'Currently in thermal paint booth for oven curing.'
      }
    ],
    qcChecklist: [],
    qcPassed: false,
    pickupRequested: true,
    deliveryRequested: true,
    discount: 100,
    taxRate: 18,
    advancePaid: 500,
    isCheckedIn: true,
    checkInRecordId: 'GATE-2026-101',
    checkedInAt: '2026-08-21 10:30 AM',
    checkInDriverName: 'Ramesh Kumar',
    checkInDriverPhone: '+91 98200 99887',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'JC-2026-102',
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    estimatedCompletionDate: new Date(Date.now() + 3600000 * 48).toISOString(),
    isUrgent: false,
    isCars24: false,
    vehicle: {
      registrationNumber: 'KA01MJ8821',
      make: 'Hyundai',
      model: 'Creta SX (O)',
      year: 2023,
      color: 'Titan Grey',
      vin: 'MALC181CLPM10293',
      fuelLevel: 40,
      mileage: 21800
    },
    customer: {
      id: 'cust-102',
      name: 'Ananya Verma',
      phone: '+91 98765 43210',
      email: 'ananya.verma@gmail.com',
      address: 'Flat 402, Sunshine Apartments, HSR Layout, Bengaluru'
    },
    status: 'ESTIMATE_PENDING',
    serviceType: 'STANDARD_PACKAGE',
    packageName: 'Comprehensive Periodic Service & Brakes',
    floorManagerId: 'emp-101',
    floorManagerName: 'Rajesh Sharma (Floor Manager)',
    cityName: 'Bengaluru',
    workshopName: 'FixoCar Hub - HSR Layout',
    tasks: [
      {
        id: 'task-102-1',
        jobCardId: 'JC-2026-102',
        title: 'Synthetic Engine Oil & Filter Change',
        category: 'MECHANICAL',
        assignedToId: 'emp-103',
        assignedToName: 'Suresh Patel (Mechanic)',
        assignedType: 'EMPLOYEE',
        estimatedCost: 1800,
        customerPrice: 2800,
        status: 'PENDING',
        requiresCustomerApproval: true,
        notes: 'Awaiting customer estimate confirmation.'
      }
    ],
    qcChecklist: [],
    qcPassed: false,
    pickupRequested: false,
    deliveryRequested: true,
    discount: 0,
    taxRate: 18,
    advancePaid: 0,
    isCheckedIn: true,
    checkInRecordId: 'GATE-2026-102',
    checkedInAt: '2026-08-22 02:15 PM',
    checkInDriverName: 'Ananya Verma (Self)',
    checkInDriverPhone: '+91 98765 43210',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'JC-2026-103',
    createdAt: new Date(Date.now() - 3600000 * 72).toISOString(),
    estimatedCompletionDate: new Date(Date.now() - 3600000 * 6).toISOString(),
    isUrgent: false,
    isCars24: true,
    cars24RefNo: 'C24-DEL-9912',
    vehicle: {
      registrationNumber: 'DL03CE1234',
      make: 'Honda',
      model: 'City VX',
      year: 2021,
      color: 'Golden Brown',
      vin: 'MAKGM2680L001928',
      fuelLevel: 80,
      mileage: 42100
    },
    customer: {
      id: 'cust-103',
      name: 'Cars24 Yard - Okhla Phase 3',
      phone: '+91 98112 33445',
      email: 'okhla.yard@cars24.com',
      address: 'Plot 88, Okhla Industrial Estate Phase 3, New Delhi'
    },
    status: 'READY_FOR_DELIVERY',
    serviceType: 'ACCIDENT_BODYWORK',
    packageName: 'Front & Rear Bumper Refinishing',
    floorManagerId: 'emp-101',
    floorManagerName: 'Rajesh Sharma (Floor Manager)',
    cityName: 'Delhi NCR',
    workshopName: 'FixoCar Mega Workshop - Okhla',
    tasks: [
      {
        id: 'task-103-1',
        jobCardId: 'JC-2026-103',
        title: 'Front Bumper Dent Repair & Refinishing',
        category: 'PAINT',
        assignedToId: 'emp-105',
        assignedToName: 'Kenji Sato (Painter)',
        assignedType: 'EMPLOYEE',
        estimatedCost: 750,
        customerPrice: 1350,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        notes: 'Final clear coat cured and polished.'
      }
    ],
    qcChecklist: [],
    qcPassed: true,
    qcPassedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    pickupRequested: true,
    deliveryRequested: true,
    discount: 50,
    taxRate: 18,
    advancePaid: 1000,
    isCheckedIn: true,
    checkInRecordId: 'GATE-2026-103',
    checkedInAt: '2026-08-20 11:00 AM',
    checkInDriverName: 'Vikram Singh (Logistics)',
    checkInDriverPhone: '+91 98112 99001',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80'
  }
];

export const INITIAL_VEHICLE_CHECKINS: VehicleCheckIn[] = [
  {
    id: 'GATE-2026-101',
    registrationNumber: 'MH02CB9988',
    make: 'Maruti Suzuki',
    model: 'Swift',
    variant: 'VXi',
    fuelType: 'Petrol',
    color: 'Arctic White',
    fuelLevel: 65,
    mileage: 34500,
    isCars24: true,
    cars24RefNo: 'C24-MUM-8821',
    customerName: 'Cars24 Hub - Andheri West',
    customerPhone: '+91 98200 11223',
    checkedInAt: '2026-08-21 10:30 AM',
    checkedInByName: 'Gate Security / Manager',
    checkInDriverName: 'Ramesh Kumar (Logistics)',
    checkInDriverPhone: '+91 98200 99887',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    checkInNotes: 'Arrived via driver. Vehicle received with minor denting on bonnet. In workshop for active repair.',
    status: 'JOB_CARD_CREATED',
    jobCardId: 'JC-2026-101'
  },
  {
    id: 'GATE-2026-102',
    registrationNumber: 'KA01MJ8821',
    make: 'Hyundai',
    model: 'Creta',
    variant: 'SX (O)',
    fuelType: 'Diesel',
    color: 'Titan Grey',
    fuelLevel: 40,
    mileage: 21800,
    isCars24: false,
    customerName: 'Ananya Verma',
    customerPhone: '+91 98765 43210',
    checkedInAt: '2026-08-22 02:15 PM',
    checkedInByName: 'Gate Security / Manager',
    checkInDriverName: 'Ananya Verma (Self Drive)',
    checkInDriverPhone: '+91 98765 43210',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    checkInNotes: 'Customer brought in for periodic service. Waiting for estimate approval.',
    status: 'AWAITING_JOB_CARD',
    jobCardId: 'JC-2026-102'
  },
  {
    id: 'GATE-2026-103',
    registrationNumber: 'DL03CE1234',
    make: 'Honda',
    model: 'City',
    variant: 'VX',
    fuelType: 'Petrol',
    color: 'Golden Brown',
    fuelLevel: 80,
    mileage: 42100,
    isCars24: true,
    cars24RefNo: 'C24-DEL-9912',
    customerName: 'Cars24 Yard - Okhla Phase 3',
    customerPhone: '+91 98112 33445',
    checkedInAt: '2026-08-20 11:00 AM',
    checkedInByName: 'Gate Security / Manager',
    checkInDriverName: 'Vikram Singh (Logistics)',
    checkInDriverPhone: '+91 98112 99001',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    checkInNotes: 'Bumper paint job completed. Vehicle QC passed & ready for dispatch.',
    status: 'READY_PENDING_DISPATCH',
    jobCardId: 'JC-2026-103'
  },
  {
    id: 'GATE-2026-104',
    registrationNumber: 'MH12PA5544',
    make: 'Tata',
    model: 'Nexon',
    variant: 'XZ+',
    fuelType: 'EV',
    color: 'Foliage Green',
    fuelLevel: 90,
    mileage: 18900,
    isCars24: true,
    cars24RefNo: 'C24-PUN-3310',
    customerName: 'Cars24 Hub - Baner Pune',
    customerPhone: '+91 98220 44556',
    checkedInAt: '2026-08-19 09:15 AM',
    checkedInByName: 'Gate Security / Manager',
    checkInDriverName: 'Sanjay Dutt',
    checkInDriverPhone: '+91 98220 99881',
    checkInPhotoWithDriverUrl: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80',
    checkInNotes: 'Preliminary inspection completed. Waiting for Cars24 WSM estimate approval.',
    status: 'IDLE_AWAITING_PI'
  }
];
