import { Employee, Vendor, JobCard, StandardServicePackage, PurchaseOrder, DeliveryRecord, CityServiceOffering, ServiceBookingRequest, InventoryItem, StandardJob } from '../types';

export const INITIAL_CITY_SERVICES: CityServiceOffering[] = [
  {
    id: 'srv-periodic-30',
    title: 'Comprehensive Periodic Service',
    category: 'MECHANICAL',
    tagline: 'Complete 30-Point Check, Synthetic Engine Oil, Oil & Air Filter Replacement, OBD-II Scan',
    description: 'Full periodic engine tune-up with synthetic oil flush, spark plug checks, brake pad wear inspection, coolant top-up, and eco steam wash.',
    estimatedHours: 3.5,
    isPopular: true,
    cityPrices: {
      'Mumbai': 3499,
      'Delhi NCR': 2999,
      'Bengaluru': 3299,
      'Hyderabad': 2899,
      'Pune': 2999,
      'Chennai': 2899,
      'Jaipur': 2499,
      'Ahmedabad': 2599,
      'Chandigarh': 2699,
      'Kolkata': 2799,
    },
    includedFeatures: [
      'Synthetic Engine Oil (up to 4L) & Filter Replacement',
      'Cabin Air Filter & Fuel Line Cleaning',
      '30-Point Computerized OBD-II Diagnostics Scan',
      'Brake Pad & Rotor Thickness Check',
      'Coolant, Brake Fluid & Battery Top-Up',
      'Complimentary Interior Vacuum & Eco Steam Wash'
    ]
  },
  {
    id: 'srv-ac-chilling',
    title: 'AC Deep Chilling & Gas Refill',
    category: 'MECHANICAL',
    tagline: 'High-grade R134a Gas Recharge, Condenser Cleaning, Leak Test & Antibacterial Treatment',
    description: 'Beat the heat with full AC system diagnostics, vacuum leak testing, condenser pressure wash, and fresh R134a gas recharge.',
    estimatedHours: 2,
    isPopular: true,
    cityPrices: {
      'Mumbai': 2499,
      'Delhi NCR': 2199,
      'Bengaluru': 2299,
      'Hyderabad': 1999,
      'Pune': 2099,
      'Chennai': 2199,
      'Jaipur': 1899,
      'Ahmedabad': 1999,
      'Chandigarh': 1999,
      'Kolkata': 2099,
    },
    includedFeatures: [
      'Environment Friendly R134a Gas Top-Up',
      'Compressor Oil & Leakage Vacuum Testing',
      'Condenser & Cooling Coil Pressure Wash',
      'AC Vent Antibacterial Foam Cleaning',
      'Cabin AC Dust Filter Cleaning / Replacement Check'
    ]
  },
  {
    id: 'srv-brake-alignment',
    title: 'Brake Overhaul & 3D Wheel Alignment',
    category: 'MECHANICAL',
    tagline: 'Front & Rear Brake Pad Renewal, Rotor Lathe Resurfacing & 3D Laser Alignment',
    description: 'Ensure maximum stopping safety and smooth steering stability with precision brake overhaul and 3D laser alignment.',
    estimatedHours: 3,
    isPopular: false,
    cityPrices: {
      'Mumbai': 4299,
      'Delhi NCR': 3899,
      'Bengaluru': 3999,
      'Hyderabad': 3699,
      'Pune': 3799,
      'Chennai': 3599,
      'Jaipur': 3299,
      'Ahmedabad': 3399,
      'Chandigarh': 3499,
      'Kolkata': 3499,
    },
    includedFeatures: [
      'Front Ceramic Brake Pad Replacement',
      'Brake Disc Rotor Skimming & Lathe Resurfacing',
      'Brake Fluid Bleeding & Flushing (DOT 4)',
      'Computerized 3D Laser Wheel Alignment',
      '4-Wheel Dynamic Balancing & Tire Rotation'
    ]
  },
  {
    id: 'srv-denting-painting',
    title: 'Panel Denting & Paint Restoration',
    category: 'PAINT',
    tagline: 'Precision Metal Pulling, Anti-Rust Primer & Heated Booth Metallic Painting',
    description: 'Flawless panel paint restoration using computerized color matching, anti-corrosion primer, and clear coat baking.',
    estimatedHours: 6,
    isPopular: true,
    cityPrices: {
      'Mumbai': 3200,
      'Delhi NCR': 2800,
      'Bengaluru': 2999,
      'Hyderabad': 2600,
      'Pune': 2700,
      'Chennai': 2600,
      'Jaipur': 2400,
      'Ahmedabad': 2500,
      'Chandigarh': 2500,
      'Kolkata': 2600,
    },
    includedFeatures: [
      'Panel Dent Pulling & Surface Leveling',
      'Anti-Rust Epoxy Primer Coat',
      '3-Layer High Temperature Baked Metallic Paint',
      '3M Buffing, Polishing & Clear Coat Sealant',
      '2-Year Paint Color Protection Warranty'
    ]
  },
  {
    id: 'srv-interior-detailing',
    title: 'Full Interior Spa & Ceramic Polishing',
    category: 'WASHING',
    tagline: 'Deep Upholstery Steam Wash, Dashboard Protection & Exterior Ceramic Shield',
    description: 'Transform your vehicle inside and out with deep interior foam extraction and hydrophobic paint ceramic polish.',
    estimatedHours: 4,
    isPopular: false,
    cityPrices: {
      'Mumbai': 3999,
      'Delhi NCR': 3499,
      'Bengaluru': 3699,
      'Hyderabad': 3299,
      'Pune': 3399,
      'Chennai': 3299,
      'Jaipur': 2999,
      'Ahmedabad': 3099,
      'Chandigarh': 3199,
      'Kolkata': 3199,
    },
    includedFeatures: [
      'Hot Steam Interior Upholstery Wash & Stain Removal',
      'Dashboard & Leather Trim UV Conditioning',
      'Ozone Sanitization & Odor Eliminator',
      'High-Gloss Paint Buffing & Ceramic Paste Wax',
      'Engine Bay Detailing & Rubber Dressing'
    ]
  },
  {
    id: 'srv-clutch-transmission',
    title: 'Clutch Assembly Overhaul',
    category: 'MECHANICAL',
    tagline: 'Clutch Plate & Pressure Plate Renewal, Release Bearing & Gear Oil Flush',
    description: 'Eliminate clutch slippage, harsh gear shifts, and poor pickup with genuine OEM clutch replacement.',
    estimatedHours: 5,
    isPopular: false,
    cityPrices: {
      'Mumbai': 8499,
      'Delhi NCR': 7499,
      'Bengaluru': 7999,
      'Hyderabad': 7299,
      'Pune': 7399,
      'Chennai': 7199,
      'Jaipur': 6899,
      'Ahmedabad': 6999,
      'Chandigarh': 7099,
      'Kolkata': 7199,
    },
    includedFeatures: [
      'OEM Clutch Plate & Pressure Plate Replacement',
      'Clutch Release Bearing Installation',
      'Flywheel Facing & Alignment Check',
      'Synthetic Gearbox Oil Flush & Refill',
      'Clutch Cable / Hydraulic Cylinder Bleeding'
    ]
  }
];

export const INITIAL_SERVICE_BOOKINGS: ServiceBookingRequest[] = [
  {
    id: 'BOOK-901',
    city: 'Mumbai',
    serviceId: 'srv-periodic-30',
    serviceTitle: 'Comprehensive Periodic Service',
    price: 3499,
    customerName: 'Rohit Verma',
    customerPhone: '8819915656',
    customerEmail: 'rohit.verma@example.com',
    vehicleNumber: 'MH-02-CB-9912',
    vehicleMakeModel: 'Hyundai Creta 1.5 SX',
    preferredDate: '2026-07-27',
    preferredTimeSlot: '10:00 AM - 12:00 PM',
    address: 'B-304, Sea Green Towers, Bandra West, Mumbai',
    pickupNeeded: true,
    createdAt: '2026-07-26 08:30 AM',
    status: 'CONFIRMED',
    createdJobCardId: 'JC-2026-101'
  },
  {
    id: 'BOOK-902',
    city: 'Delhi NCR',
    serviceId: 'srv-ac-chilling',
    serviceTitle: 'AC Deep Chilling & Gas Refill',
    price: 2199,
    customerName: 'Ananya Gupta',
    customerPhone: '8819915656',
    customerEmail: 'ananya.g@example.com',
    vehicleNumber: 'DL-04-CA-1100',
    vehicleMakeModel: 'Mercedes-Benz C200',
    preferredDate: '2026-07-26',
    preferredTimeSlot: '02:00 PM - 04:00 PM',
    address: 'Sector 44, Gurugram, Delhi NCR',
    pickupNeeded: false,
    createdAt: '2026-07-26 09:15 AM',
    status: 'IN_REPAIR',
    createdJobCardId: 'JC-2026-104'
  }
];

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-101',
    name: 'Marcus Vance',
    role: 'FLOOR_MANAGER',
    phone: '8819915656',
    email: 'marcus.vance@fixocar.com',
    specializedTeam: 'Management',
    status: 'AVAILABLE',
    activeJobsCount: 4,
    employmentType: 'PAYROLL',
    workshopId: 'ws-mumbai-central',
    workshopName: 'FixoCar Central Hub - Andheri',
    cityId: 'city-mumbai',
    cityName: 'Mumbai',
  },
  {
    id: 'emp-102',
    name: 'Rajesh Sharma',
    role: 'MECHANIC',
    phone: '8819915656',
    email: 'rajesh.mechanic@fixocar.com',
    specializedTeam: 'Mechanical',
    status: 'BUSY',
    activeJobsCount: 2,
    employmentType: 'PAYROLL',
    workshopId: 'ws-mumbai-central',
    workshopName: 'FixoCar Central Hub - Andheri',
    cityId: 'city-mumbai',
    cityName: 'Mumbai',
  },
  {
    id: 'emp-103',
    name: 'Carlos Ruiz',
    role: 'MECHANIC',
    phone: '8819915656',
    email: 'carlos.ruiz@fixocar.com',
    specializedTeam: 'Mechanical',
    status: 'AVAILABLE',
    activeJobsCount: 1,
    employmentType: 'PAYROLL',
    workshopId: 'ws-mumbai-central',
    workshopName: 'FixoCar Central Hub - Andheri',
    cityId: 'city-mumbai',
    cityName: 'Mumbai',
  },
  {
    id: 'emp-104',
    name: 'David O\'Connor',
    role: 'DENTER',
    phone: '8819915656',
    email: 'david.denter@fixocar.com',
    specializedTeam: 'Denting',
    status: 'BUSY',
    activeJobsCount: 2,
    employmentType: 'CONTRACT',
    workshopId: 'ws-delhi-south',
    workshopName: 'FixoCar Fleet Bay - Okhla',
    cityId: 'city-delhi',
    cityName: 'Delhi NCR',
  },
  {
    id: 'emp-105',
    name: 'Kenji Sato',
    role: 'PAINTER',
    phone: '8819915656',
    email: 'kenji.paint@fixocar.com',
    specializedTeam: 'Paint',
    status: 'BUSY',
    activeJobsCount: 1,
    employmentType: 'CONTRACT',
    workshopId: 'ws-delhi-south',
    workshopName: 'FixoCar Fleet Bay - Okhla',
    cityId: 'city-delhi',
    cityName: 'Delhi NCR',
  },
  {
    id: 'emp-106',
    name: 'Alex Rivera',
    role: 'DELIVERY_BOY',
    phone: '8819915656',
    email: 'alex.logistics@fixocar.com',
    specializedTeam: 'Logistics',
    status: 'BUSY',
    activeJobsCount: 1,
    employmentType: 'PAYROLL',
    workshopId: 'ws-mumbai-central',
    workshopName: 'FixoCar Central Hub - Andheri',
    cityId: 'city-mumbai',
    cityName: 'Mumbai',
  },
  {
    id: 'emp-107',
    name: 'Sarah Chen',
    role: 'ADMIN',
    phone: '8819915656',
    email: 'sarah.admin@fixocar.com',
    specializedTeam: 'Management',
    status: 'AVAILABLE',
    activeJobsCount: 0,
    employmentType: 'PAYROLL',
    workshopId: 'ws-mumbai-central',
    workshopName: 'FixoCar Central Hub - Andheri',
    cityId: 'city-mumbai',
    cityName: 'Mumbai',
  },
];

export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'ven-201',
    name: 'Apex Auto Spare Parts Ltd',
    category: 'PARTS_SUPPLIER',
    contactPerson: 'Robert Miller',
    phone: '+1 (555) 111-2233',
    email: 'orders@apexautoparts.com',
    address: '45 Industrial Park Avenue',
    outstandingBalance: 1450,
    rating: 4.8,
  },
  {
    id: 'ven-202',
    name: 'Precision Lathe & Cylinder Boring',
    category: 'LATHE_WORK',
    contactPerson: 'Vikram Patel',
    phone: '+1 (555) 222-3344',
    email: 'service@precisionlathe.com',
    address: '88 Lathe Works Estate',
    outstandingBalance: 14500,
    rating: 4.8,
  },
  {
    id: 'ven-202',
    name: 'Precision Lathe & Cylinder Boring',
    category: 'LATHE_WORK',
    contactPerson: 'Vikram Patel',
    phone: '8819915656',
    email: 'service@precisionlathe.com',
    address: '88 Lathe Works Estate',
    outstandingBalance: 6200,
    rating: 4.9,
  },
  {
    id: 'ven-203',
    name: 'AquaSpa Eco Steam Wash & Detailing',
    category: 'WASHING',
    contactPerson: 'Linda Thorne',
    phone: '8819915656',
    email: 'clean@aquaspawash.com',
    address: '12 Hydro Street',
    outstandingBalance: 3200,
    rating: 4.7,
  },
  {
    id: 'ven-204',
    name: 'VoltTech Auto Electricals',
    category: 'ELECTRICIAN',
    contactPerson: 'Ahmed Hassan',
    phone: '8819915656',
    email: 'support@volttech.com',
    address: '102 Spark Lane',
    outstandingBalance: 0,
    rating: 4.6,
  },
];

export const STANDARD_PACKAGES: StandardServicePackage[] = [
  {
    id: 'pkg-full-service',
    name: 'Comprehensive Periodic Service (30-Point)',
    tagline: 'Complete mechanical tune-up, fluid replacement & 30-point safety check',
    basePrice: 3499,
    estimatedHours: 4,
    includedTasks: [
      { title: 'Engine Oil & Filter Replacement (Synthetic 5W-30)', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 1200, price: 1850 },
      { title: 'Air Filter & Cabin AC Filter Replacement', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 350, price: 650 },
      { title: 'Brake Pad & Rotor Wear Thickness Inspection', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 200, price: 400 },
      { title: 'Spark Plug & Ignition Coil Test', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 300, price: 500 },
      { title: 'Coolant & Transmission Fluid Top-up', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 250, price: 450 },
      { title: '30-Point Computerized OBD-II Diagnostics Scan', category: 'INSPECTION', defaultTeam: 'Management', estimatedCost: 300, price: 600 },
      { title: 'Eco Steam Wash & Interior Vacuuming (Sublet)', category: 'WASHING', defaultTeam: 'Detailing & Washing', estimatedCost: 250, price: 500 },
    ]
  },
  {
    id: 'pkg-brake-suspension',
    name: 'Brake Overhaul & Suspension Alignment',
    tagline: 'Front & Rear brake pad renewal, rotor resurfacing and 3D wheel alignment',
    basePrice: 4299,
    estimatedHours: 5,
    includedTasks: [
      { title: 'Front Ceramic Brake Pad Replacement', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 1400, price: 2200 },
      { title: 'Brake Disc Lathe Resurfacing (Sublet Lathe)', category: 'SUBLET_VENDOR', defaultTeam: 'Sublet / Lathe', estimatedCost: 600, price: 1100 },
      { title: 'Brake Fluid Flushing & Bleeding (DOT 4)', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 300, price: 600 },
      { title: 'Suspension Bushing & Strut Inspection', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 200, price: 450 },
      { title: '3D Laser Wheel Alignment & Balancing', category: 'MECHANICAL', defaultTeam: 'Mechanical', estimatedCost: 400, price: 850 },
    ]
  },
  {
    id: 'pkg-body-paint',
    name: 'Denting & Panel Paint Restoration',
    tagline: 'Precision metal pulling, primer coat & booth baked ceramic lacquer paint',
    basePrice: 3200,
    estimatedHours: 8,
    includedTasks: [
      { title: 'Panel Dent Pulling & Surface Leveling', category: 'DENTING', defaultTeam: 'Denting', estimatedCost: 800, price: 1500 },
      { title: 'Anti-Rust Epoxy Primer Application', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 400, price: 800 },
      { title: 'High-Temperature Baked Metallic Paint & Clear Coat', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 1200, price: 2200 },
      { title: '3M Buffing, Polishing & Paint Protection Sealant', category: 'PAINT', defaultTeam: 'Paint', estimatedCost: 300, price: 700 },
    ]
  }
];

export const INITIAL_DELIVERIES: DeliveryRecord[] = [
  {
    id: 'del-301',
    jobCardId: 'JC-2026-102',
    vehicleReg: 'KA-01-MJ-8821',
    customerName: 'Aarav Sharma',
    customerPhone: '8819915656',
    deliveryBoyId: 'emp-106',
    deliveryBoyName: 'Alex Rivera',
    deliveryBoyPhone: '8819915656',
    type: 'DELIVERY',
    pickupAddress: 'FixoCar Workshop Central',
    deliveryAddress: '742 Evergreen Terrace, Sector 4, Metro City',
    status: 'OUT_FOR_DELIVERY',
    totalAmountDue: 4850,
    paymentStatus: 'PENDING',
    currentLat: 37.7749,
    currentLng: -122.4194,
    destinationLat: 37.7833,
    destinationLng: -122.4167,
    etaMinutes: 18,
    notes: 'Customer requested phone call 5 mins prior to arrival. Prefers UPI/Card payment.',
  }
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'PO-9001',
    jobCardId: 'JC-2026-101',
    vehicleReg: 'MH-02-CB-9912',
    vendorId: 'ven-201',
    vendorName: 'Apex Auto Spare Parts Ltd',
    category: 'PARTS_SUPPLIER',
    itemDescription: 'OEM Toyota Brake Pads & Oil Filter Set',
    amount: 2450,
    status: 'DELIVERED',
    createdAt: '2026-07-25 10:30 AM',
  },
  {
    id: 'PO-9002',
    jobCardId: 'JC-2026-102',
    vehicleReg: 'KA-01-MJ-8821',
    vendorId: 'ven-202',
    vendorName: 'Precision Lathe & Cylinder Boring',
    category: 'LATHE_WORK',
    itemDescription: 'Front Rotor Disc Facing & Skimming',
    amount: 1200,
    status: 'PAID',
    createdAt: '2026-07-25 02:15 PM',
  },
];

export const INITIAL_JOB_CARDS: JobCard[] = [
  {
    id: 'JC-2026-101',
    createdAt: '2026-07-25 09:15 AM',
    estimatedCompletionDate: '2026-07-26 05:00 PM',
    vehicle: {
      registrationNumber: 'MH-02-CB-9912',
      make: 'Hyundai',
      model: 'Creta 1.5 SX',
      year: 2022,
      color: 'Titan Grey',
      vin: '1HGCR2F83MA012984',
      fuelLevel: 65,
      mileage: 42500,
    },
    customer: {
      id: 'cust-501',
      name: 'Rohit Verma',
      phone: '8819915656',
      email: 'rohit.verma@example.com',
      address: 'B-304, Sea Green Towers, Bandra West, Mumbai',
    },
    status: 'IN_PROGRESS',
    serviceType: 'STANDARD_PACKAGE',
    packageName: 'Comprehensive Periodic Service (30-Point)',
    floorManagerId: 'emp-101',
    floorManagerName: 'Marcus Vance',
    pickupRequested: true,
    deliveryRequested: true,
    discount: 200,
    taxRate: 18,
    advancePaid: 1000,
    tasks: [
      {
        id: 'task-101-1',
        jobCardId: 'JC-2026-101',
        title: 'Engine Oil & Synthetic Filter Replacement',
        category: 'MECHANICAL',
        assignedToId: 'emp-102',
        assignedToName: 'Rajesh Sharma',
        assignedType: 'EMPLOYEE',
        estimatedCost: 1200,
        customerPrice: 1850,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
        notes: 'Used Shell Helix Ultra 5W-30',
        completedAt: '2026-07-25 11:30 AM',
      },
      {
        id: 'task-101-2',
        jobCardId: 'JC-2026-101',
        title: 'Front Brake Pad & Disc Inspection',
        category: 'MECHANICAL',
        assignedToId: 'emp-102',
        assignedToName: 'Rajesh Sharma',
        assignedType: 'EMPLOYEE',
        estimatedCost: 200,
        customerPrice: 450,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-101-3',
        jobCardId: 'JC-2026-101',
        title: 'Worn Rear Shock Absorber Replacement (Additional Issue Found)',
        category: 'MECHANICAL',
        assignedToId: 'emp-103',
        assignedToName: 'Carlos Ruiz',
        assignedType: 'EMPLOYEE',
        estimatedCost: 2800,
        customerPrice: 4500,
        status: 'PENDING',
        requiresCustomerApproval: true,
        isCustomerApproved: null, // Awaiting customer approval
        notes: 'Fluid leaking from left rear strut assembly. Requires replacement.',
      },
    ],
    qcChecklist: [
      { id: 'qc-1', label: 'Engine oil cap & dipstick tightened', category: 'ENGINE', isPassed: true },
      { id: 'qc-2', label: 'Brake fluid reservoir level checked', category: 'ENGINE', isPassed: true },
      { id: 'qc-3', label: 'Wheel lug nuts torque check', category: 'BODY', isPassed: true },
      { id: 'qc-4', label: 'Tire pressure balanced (32 PSI)', category: 'BODY', isPassed: false },
      { id: 'qc-5', label: 'Interior seat & dashboard protection removed', category: 'INTERIOR', isPassed: false },
      { id: 'qc-6', label: 'Road test - no vibration/noise', category: 'TEST_DRIVE', isPassed: false },
    ],
    qcPassed: false,
  },
  {
    id: 'JC-2026-102',
    createdAt: '2026-07-25 11:00 AM',
    estimatedCompletionDate: '2026-07-26 02:00 PM',
    vehicle: {
      registrationNumber: 'KA-01-MJ-8821',
      make: 'BMW',
      model: '330i M Sport',
      year: 2022,
      color: 'Alpine White',
      vin: 'WBA5R1C51KFK82019',
      fuelLevel: 80,
      mileage: 28400,
    },
    customer: {
      id: 'cust-502',
      name: 'Aarav Sharma',
      phone: '8819915656',
      email: 'aarav.sharma@example.com',
      address: '742 Evergreen Terrace, Sector 4, Metro City',
    },
    status: 'OUT_FOR_DELIVERY',
    serviceType: 'STANDARD_PACKAGE',
    packageName: 'Brake Overhaul & Suspension Alignment',
    floorManagerId: 'emp-101',
    floorManagerName: 'Marcus Vance',
    pickupRequested: true,
    deliveryRequested: true,
    deliveryRecordId: 'del-301',
    discount: 300,
    taxRate: 18,
    advancePaid: 0,
    tasks: [
      {
        id: 'task-102-1',
        jobCardId: 'JC-2026-102',
        title: 'Front Ceramic Brake Pad Replacement',
        category: 'MECHANICAL',
        assignedToId: 'emp-102',
        assignedToName: 'Rajesh Sharma',
        assignedType: 'EMPLOYEE',
        estimatedCost: 1400,
        customerPrice: 2200,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-102-2',
        jobCardId: 'JC-2026-102',
        title: 'Brake Disc Lathe Resurfacing',
        category: 'SUBLET_VENDOR',
        assignedToId: 'ven-202',
        assignedToName: 'Precision Lathe & Cylinder Boring',
        assignedType: 'VENDOR',
        estimatedCost: 600,
        customerPrice: 1100,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-102-3',
        jobCardId: 'JC-2026-102',
        title: '3D Laser Wheel Alignment & Balancing',
        category: 'MECHANICAL',
        assignedToId: 'emp-103',
        assignedToName: 'Carlos Ruiz',
        assignedType: 'EMPLOYEE',
        estimatedCost: 400,
        customerPrice: 850,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-102-4',
        jobCardId: 'JC-2026-102',
        title: 'Eco Steam Wash & Detailing',
        category: 'WASHING',
        assignedToId: 'ven-203',
        assignedToName: 'AquaSpa Eco Steam Wash & Detailing',
        assignedType: 'VENDOR',
        estimatedCost: 300,
        customerPrice: 700,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      }
    ],
    qcChecklist: [
      { id: 'qc-1', label: 'Engine oil cap & dipstick tightened', category: 'ENGINE', isPassed: true },
      { id: 'qc-2', label: 'Brake fluid reservoir level checked', category: 'ENGINE', isPassed: true },
      { id: 'qc-3', label: 'Wheel lug nuts torque check', category: 'BODY', isPassed: true },
      { id: 'qc-4', label: 'Tire pressure balanced (32 PSI)', category: 'BODY', isPassed: true },
      { id: 'qc-5', label: 'Interior seat & dashboard protection removed', category: 'INTERIOR', isPassed: true },
      { id: 'qc-6', label: 'Road test - no vibration/noise', category: 'TEST_DRIVE', isPassed: true },
    ],
    qcPassed: true,
    qcPassedAt: '2026-07-25 04:30 PM',
  },
  {
    id: 'JC-2026-103',
    createdAt: '2026-07-26 08:30 AM',
    estimatedCompletionDate: '2026-07-27 06:00 PM',
    vehicle: {
      registrationNumber: 'MH-12-PQ-4409',
      make: 'Hyundai',
      model: 'Tucson 2.0 CRDi',
      year: 2023,
      color: 'Phantom Black',
      vin: 'KM8J33A25PU910238',
      fuelLevel: 40,
      mileage: 18200,
    },
    customer: {
      id: 'cust-503',
      name: 'Priya Narang',
      phone: '8819915656',
      email: 'priya.n@example.com',
      address: '22 Ocean View Boulevard, Pune',
    },
    status: 'IN_PROGRESS',
    serviceType: 'ACCIDENT_BODYWORK',
    floorManagerId: 'emp-101',
    floorManagerName: 'Marcus Vance',
    pickupRequested: false,
    deliveryRequested: true,
    discount: 0,
    taxRate: 18,
    advancePaid: 2000,
    tasks: [
      {
        id: 'task-103-1',
        jobCardId: 'JC-2026-103',
        title: 'Right Front Door & Fender Dent Pulling',
        category: 'DENTING',
        assignedToId: 'emp-104',
        assignedToName: 'David O\'Connor',
        assignedType: 'EMPLOYEE',
        estimatedCost: 1200,
        customerPrice: 2800,
        status: 'IN_PROGRESS',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-103-2',
        jobCardId: 'JC-2026-103',
        title: 'Bake Booth Phantom Black Metallic Painting',
        category: 'PAINT',
        assignedToId: 'emp-105',
        assignedToName: 'Kenji Sato',
        assignedType: 'EMPLOYEE',
        estimatedCost: 1800,
        customerPrice: 3800,
        status: 'PENDING',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-103-3',
        jobCardId: 'JC-2026-103',
        title: 'Replace Right Wing Mirror Assembly (Sublet Parts)',
        category: 'PARTS',
        assignedToId: 'ven-201',
        assignedToName: 'Apex Auto Spare Parts Ltd',
        assignedType: 'VENDOR',
        estimatedCost: 1500,
        customerPrice: 2500,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      }
    ],
    qcChecklist: [
      { id: 'qc-1', label: 'Engine oil cap & dipstick tightened', category: 'ENGINE', isPassed: true },
      { id: 'qc-2', label: 'Brake fluid reservoir level checked', category: 'ENGINE', isPassed: true },
      { id: 'qc-3', label: 'Wheel lug nuts torque check', category: 'BODY', isPassed: false },
      { id: 'qc-4', label: 'Tire pressure balanced (32 PSI)', category: 'BODY', isPassed: false },
      { id: 'qc-5', label: 'Interior seat & dashboard protection removed', category: 'INTERIOR', isPassed: false },
      { id: 'qc-6', label: 'Road test - no vibration/noise', category: 'TEST_DRIVE', isPassed: false },
    ],
    qcPassed: false,
  },
  {
    id: 'JC-2026-104',
    createdAt: '2026-07-26 10:00 AM',
    estimatedCompletionDate: '2026-07-26 04:00 PM',
    vehicle: {
      registrationNumber: 'DL-04-CA-1100',
      make: 'Mercedes-Benz',
      model: 'C200 d AMG Line',
      year: 2022,
      color: 'Obsidian Black',
      fuelLevel: 55,
      mileage: 31000,
    },
    customer: {
      id: 'cust-504',
      name: 'Ananya Gupta',
      phone: '8819915656',
      email: 'ananya.g@example.com',
      address: 'Sector 44, Gurugram, Delhi NCR',
    },
    status: 'ESTIMATE_PENDING',
    serviceType: 'CUSTOM_REPAIR',
    floorManagerId: 'emp-101',
    floorManagerName: 'Marcus Vance',
    pickupRequested: false,
    deliveryRequested: true,
    discount: 0,
    taxRate: 18,
    advancePaid: 0,
    tasks: [
      {
        id: 'task-104-1',
        jobCardId: 'JC-2026-104',
        title: 'AC Cooling Diagnostic & Gas Leakage Test',
        category: 'MECHANICAL',
        assignedToId: 'emp-102',
        assignedToName: 'Rajesh Sharma',
        assignedType: 'EMPLOYEE',
        estimatedCost: 500,
        customerPrice: 999,
        status: 'COMPLETED',
        requiresCustomerApproval: false,
        isCustomerApproved: true,
      },
      {
        id: 'task-104-2',
        jobCardId: 'JC-2026-104',
        title: 'AC Compressor Coil & Receiver Drier Replacement',
        category: 'MECHANICAL',
        assignedToId: 'emp-102',
        assignedToName: 'Rajesh Sharma',
        assignedType: 'EMPLOYEE',
        estimatedCost: 3500,
        customerPrice: 6500,
        status: 'PENDING',
        requiresCustomerApproval: true,
        isCustomerApproved: null, // Pending Customer Approval
        notes: 'Compressor clutch slipped during diagnostic test. Full assembly replacement needed.',
      }
    ],
    qcChecklist: [],
    qcPassed: false,
  }
];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [
  {
    id: 'inv-101',
    name: 'Fully Synthetic Engine Oil 5W-30 (1L)',
    partNumber: 'OIL-SYN-5W30',
    category: 'OILS_LUBRICANTS',
    stockQuantity: 45,
    unit: 'Liters',
    minStockAlert: 15,
    unitCost: 450,
    sellingPrice: 750,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack A-1',
    lastRestockedAt: '2026-07-20',
  },
  {
    id: 'inv-102',
    name: 'Front Brake Pads Set (Maruti Swift/Dzire/Baleno)',
    partNumber: 'BP-FR-SWIFT-01',
    category: 'SPARES',
    stockQuantity: 12,
    unit: 'Sets',
    minStockAlert: 5,
    unitCost: 950,
    sellingPrice: 1650,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack B-3',
    lastRestockedAt: '2026-07-22',
  },
  {
    id: 'inv-103',
    name: 'DOT 4 High Performance Brake Fluid (500ml)',
    partNumber: 'BF-DOT4-500',
    category: 'CONSUMABLES',
    stockQuantity: 28,
    unit: 'Bottles',
    minStockAlert: 10,
    unitCost: 180,
    sellingPrice: 350,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack A-2',
    lastRestockedAt: '2026-07-18',
  },
  {
    id: 'inv-104',
    name: 'Spin-on Engine Oil Filter (Hyundai/Kia i20/Venue/Creta)',
    partNumber: 'OF-HY-8801',
    category: 'SPARES',
    stockQuantity: 3,
    unit: 'Pcs',
    minStockAlert: 8,
    unitCost: 190,
    sellingPrice: 380,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack C-1',
    lastRestockedAt: '2026-07-10',
  },
  {
    id: 'inv-105',
    name: 'Activated Carbon Cabin AC Dust Filter',
    partNumber: 'ACF-CARB-902',
    category: 'SPARES',
    stockQuantity: 18,
    unit: 'Pcs',
    minStockAlert: 6,
    unitCost: 280,
    sellingPrice: 550,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack C-2',
    lastRestockedAt: '2026-07-25',
  },
  {
    id: 'inv-106',
    name: 'R134a AC Refrigerant Gas Can (450g)',
    partNumber: 'GAS-R134A-CAN',
    category: 'CONSUMABLES',
    stockQuantity: 0,
    unit: 'Cans',
    minStockAlert: 5,
    unitCost: 380,
    sellingPrice: 800,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack D-1',
    lastRestockedAt: '2026-07-05',
  },
  {
    id: 'inv-107',
    name: 'Engine Coolant Premix 50/50 Green (1L)',
    partNumber: 'CLT-PRM-1L',
    category: 'OILS_LUBRICANTS',
    stockQuantity: 22,
    unit: 'Liters',
    minStockAlert: 10,
    unitCost: 160,
    sellingPrice: 320,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack A-3',
    lastRestockedAt: '2026-07-15',
  },
  {
    id: 'inv-108',
    name: 'Microfiber Car Detailing Wash Towels 400GSM',
    partNumber: 'MF-TOWL-400',
    category: 'DETAILING_WASH',
    stockQuantity: 50,
    unit: 'Pcs',
    minStockAlert: 20,
    unitCost: 45,
    sellingPrice: 120,
    supplierVendorId: 'ven-2',
    supplierVendorName: 'MaxClean Waterless Wash Services',
    shelfLocation: 'Rack E-1',
    lastRestockedAt: '2026-07-24',
  },
  {
    id: 'inv-109',
    name: 'H4 Halogen Headlight Bulb 12V 60/55W',
    partNumber: 'BLB-H4-12V',
    category: 'ELECTRICAL',
    stockQuantity: 15,
    unit: 'Pcs',
    minStockAlert: 5,
    unitCost: 120,
    sellingPrice: 250,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack B-1',
    lastRestockedAt: '2026-07-19',
  },
  {
    id: 'inv-110',
    name: 'Automotive 12V Battery 45Ah Maintenance Free',
    partNumber: 'BAT-12V-45AH',
    category: 'TYRES_BATTERIES',
    stockQuantity: 4,
    unit: 'Pcs',
    minStockAlert: 2,
    unitCost: 3200,
    sellingPrice: 4800,
    supplierVendorId: 'ven-1',
    supplierVendorName: 'Bosch Genuine Auto Spares Ltd',
    shelfLocation: 'Rack F-1',
    lastRestockedAt: '2026-07-21',
  }
];

export const INITIAL_STANDARD_JOBS: StandardJob[] = [
  // Standard Exterior Paint Panels with Painter & Denter Payout Rules
  {
    id: 'std-paint-1',
    title: 'Door LHS Front - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950, // 800 Painter + 150 Denter
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-2',
    title: 'Door LHS Rear - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-3',
    title: 'Fender LHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 750,
    cars24Price: 750,
    isContractBasis: true,
    painterPayout: 550,
    denterPayout: 150,
    contractorPayout: 700,
    estimatedHours: 2,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹750, Painter: ₹550, Denter: ₹150)'
  },
  {
    id: 'std-paint-4',
    title: 'Quarter Panel LHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-5',
    title: 'Quarter Panel RHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-6',
    title: 'Running Board LHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 750,
    cars24Price: 750,
    isContractBasis: true,
    painterPayout: 400,
    denterPayout: 150,
    contractorPayout: 550,
    estimatedHours: 2,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹750, Painter: ₹400, Denter: ₹150)'
  },
  {
    id: 'std-paint-7',
    title: 'Running Board RHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 750,
    cars24Price: 750,
    isContractBasis: true,
    painterPayout: 400,
    denterPayout: 150,
    contractorPayout: 550,
    estimatedHours: 2,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹750, Painter: ₹400, Denter: ₹150)'
  },
  {
    id: 'std-paint-8',
    title: 'Fender RHS - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 750,
    cars24Price: 750,
    isContractBasis: true,
    painterPayout: 550,
    denterPayout: 150,
    contractorPayout: 700,
    estimatedHours: 2,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹750, Painter: ₹550, Denter: ₹150)'
  },
  {
    id: 'std-paint-9',
    title: 'Door RHS Front - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-10',
    title: 'Door RHS Rear - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Exterior panel sanding, primer & paint refinish (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-11',
    title: 'Bumper Rear - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Rear bumper scratch refinish & surface repair (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-12',
    title: 'Bumper Front - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 1350,
    cars24Price: 1350,
    isContractBasis: true,
    painterPayout: 800,
    denterPayout: 150,
    contractorPayout: 950,
    estimatedHours: 3,
    description: 'Front bumper scratch refinish & surface repair (Billed: ₹1350, Painter: ₹800, Denter: ₹150)'
  },
  {
    id: 'std-paint-13',
    title: 'Roof - Paint & Major Panel Alignment',
    category: 'PAINT',
    retailPrice: 2600,
    cars24Price: 2600,
    isContractBasis: true,
    painterPayout: 1600,
    denterPayout: 300, // Double for roof per rules
    contractorPayout: 1900,
    estimatedHours: 5,
    description: 'Full roof paint refinish (Billed: ₹2600, Painter: ₹1600, Denter: ₹300 [Double Roof Rate])'
  },
  {
    id: 'std-paint-14',
    title: 'Boot Floor - Paint & Underbody Protection',
    category: 'PAINT',
    retailPrice: 300,
    cars24Price: 300,
    isContractBasis: true,
    painterPayout: 200,
    denterPayout: 100,
    contractorPayout: 300,
    estimatedHours: 1,
    description: 'Trunk floor inner panel paint seal (Billed: ₹300, Painter: ₹200, Denter: ₹100)'
  },
  {
    id: 'std-paint-15',
    title: 'Hood / Bonnet - Paint & Dent Repair',
    category: 'PAINT',
    retailPrice: 2200,
    cars24Price: 2200,
    isContractBasis: true,
    painterPayout: 1300,
    denterPayout: 300,
    contractorPayout: 1600,
    estimatedHours: 4,
    description: 'Front hood/bonnet surface sanding, primer & paint refinish (Billed: ₹2200, Painter: ₹1300, Denter: ₹300)'
  },
  {
    id: 'std-dent-15',
    title: 'Bumper Crack Plastic Welding & Extra Dent Repair',
    category: 'DENTING',
    retailPrice: 650,
    cars24Price: 500,
    isContractBasis: true,
    painterPayout: 0,
    denterPayout: 350,
    contractorPayout: 350,
    estimatedHours: 1.5,
    description: 'Additional denter repair for plastic bumper crack welding and structural brackets reinforcement.'
  },
  {
    id: 'std-dent-16',
    title: 'Running Board / Sill Heavy Pulling & Realignment',
    category: 'DENTING',
    retailPrice: 850,
    cars24Price: 650,
    isContractBasis: true,
    painterPayout: 0,
    denterPayout: 450,
    contractorPayout: 450,
    estimatedHours: 2,
    description: 'Hydraulic pin pulling and structural straightening for crushed underbody sill panel.'
  },
  {
    id: 'std-job-5',
    title: 'Basic Periodic Engine Service (Oil + Filter)',
    category: 'MECHANICAL',
    retailPrice: 3499,
    cars24Price: 2699,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 2,
    description: '5W30 Synthetic oil replacement, oil filter, air filter cleanup & 30-pt safety audit.'
  },
  {
    id: 'std-job-6',
    title: 'Front Brake Pads Replacement (Pair)',
    category: 'MECHANICAL',
    retailPrice: 1850,
    cars24Price: 1450,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 1,
    description: 'Ceramic brake pad replacement and disc caliper lubrication.'
  },
  {
    id: 'std-job-7',
    title: 'Complete Clutch Plate & Release Bearing Overhaul',
    category: 'MECHANICAL',
    retailPrice: 6800,
    cars24Price: 5200,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 5,
    description: 'Transmission removal, flywheel inspection, new pressure plate & clutch friction disc installation.'
  },
  {
    id: 'std-job-8',
    title: 'AC Gas Top-Up & Condenser Chemical Flush',
    category: 'MECHANICAL',
    retailPrice: 2200,
    cars24Price: 1750,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 2,
    description: 'R134a refrigerant recharge, leak testing, and condenser coil pressure washing.'
  },
  {
    id: 'std-job-9',
    title: 'Full Foam Wash & Interior Vacuuming',
    category: 'WASHING',
    retailPrice: 650,
    cars24Price: 400,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 1,
    description: 'High pressure underbody wash, neutral pH foam body shampoo, dry wipe & vacuuming.'
  },
  {
    id: 'std-job-10',
    title: 'Complete Interior Deep Dry Cleaning & Sanitization',
    category: 'WASHING',
    retailPrice: 2400,
    cars24Price: 1800,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 3,
    description: 'Foam extraction on seats, roof liner stain removal, dashboard dressing & ozone sanitization.'
  },
  {
    id: 'std-job-11',
    title: 'Teflon Body Polish & Gloss Masking',
    category: 'WASHING',
    retailPrice: 1900,
    cars24Price: 1400,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 2,
    description: 'Dual-action machine buffing, minor swirl mark removal & PTFE protective sealant coating.'
  },
  {
    id: 'std-acc-1',
    title: 'Custom Leatherette Bucket Seat Covers Fitting',
    category: 'ACCESSORIES',
    retailPrice: 6500,
    cars24Price: 5200,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 3,
    description: 'High-density foam padded leatherette seat covers custom stitched and snug bucket fitted.'
  },
  {
    id: 'std-acc-2',
    title: '7D All-Weather Heavy Duty Floor Mats Installation',
    category: 'ACCESSORIES',
    retailPrice: 2800,
    cars24Price: 2200,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 0.5,
    description: 'Waterproof 7D carpet mats fitted with heel pad & anti-skid locking pins.'
  },
  {
    id: 'std-acc-3',
    title: '9-inch HD Android Touchscreen System & Rear Cam',
    category: 'ACCESSORIES',
    retailPrice: 9500,
    cars24Price: 7800,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 2,
    description: 'IPS display touchscreen infotainment with Wireless Apple CarPlay, Android Auto & night-vision camera.'
  },
  {
    id: 'std-lathe-1',
    title: 'Front Brake Disc Resurfacing / Skim Turning (Pair)',
    category: 'LATHE_WORK',
    retailPrice: 850,
    cars24Price: 650,
    isContractBasis: true,
    contractorPayout: 400,
    estimatedHours: 1.5,
    description: 'Precision lathe turning to eliminate brake pedal pulsation and disc scoring.'
  },
  {
    id: 'std-lathe-2',
    title: 'Engine Flywheel Facing & Surface Skimming',
    category: 'LATHE_WORK',
    retailPrice: 1100,
    cars24Price: 850,
    isContractBasis: true,
    contractorPayout: 500,
    estimatedHours: 1.5,
    description: 'Flywheel friction surface truing on precision lathe machine for smooth clutch engagement.'
  },
  {
    id: 'std-align-1',
    title: '3D Computerized Wheel Alignment & Steering Center',
    category: 'ALIGNMENT_BALANCING',
    retailPrice: 550,
    cars24Price: 400,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 0.5,
    description: 'High-precision 3D laser alignment sensor check, camber/caster/toe correction & steering recalibration.'
  },
  {
    id: 'std-align-2',
    title: '4-Wheel Dynamic Precision Balancing & Weights',
    category: 'ALIGNMENT_BALANCING',
    retailPrice: 650,
    cars24Price: 480,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 0.5,
    description: 'Dynamic wheel balancer spin testing and lead counter-weight placement for all 4 wheels.'
  },
  {
    id: 'std-tyre-1',
    title: 'Tubeless Tyre Mounting, Valve & Balancing (Single)',
    category: 'TYRE_WORK',
    retailPrice: 350,
    cars24Price: 250,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 0.5,
    description: 'Pneumatic tyre changer dismounting/mounting, new brass valve stem & wheel balancing.'
  },
  {
    id: 'std-tyre-2',
    title: 'Heavy Duty Tubeless Puncture Vulcanization Repair',
    category: 'TYRE_WORK',
    retailPrice: 250,
    cars24Price: 180,
    isContractBasis: false,
    contractorPayout: 0,
    estimatedHours: 0.3,
    description: 'Internal mushroom patch vulcanization repair for sidewall or tread punctures.'
  }
];

