import { 
  Employee, Vendor, JobCard, StandardServicePackage, PurchaseOrder, 
  DeliveryRecord, CityServiceOffering, ServiceBookingRequest, InventoryItem, 
  StandardJob, VehicleCheckIn, Workshop 
} from '../types';

export const INITIAL_CITY_SERVICES: CityServiceOffering[] = [];

export const INITIAL_SERVICE_BOOKINGS: ServiceBookingRequest[] = [];

export const DEFAULT_SUPER_ADMIN: Employee = {
  id: 'emp-admin',
  name: 'Super Admin',
  role: 'SUPER_ADMIN',
  phone: '9820011223',
  email: 'admin@workshop.fixocar.com',
  specializedTeam: 'Management',
  status: 'AVAILABLE',
  activeJobsCount: 0,
  loginId: 'admin',
  password: 'password123',
  baseSalary: 120000,
  employmentType: 'PAYROLL'
};

export const INITIAL_EMPLOYEES: Employee[] = [
  DEFAULT_SUPER_ADMIN,
  {
    id: 'emp-mech1',
    name: 'Rajesh Kumar',
    role: 'MECHANIC',
    phone: '9820011224',
    email: 'mech1@workshop.fixocar.com',
    specializedTeam: 'Mechanical',
    status: 'AVAILABLE',
    activeJobsCount: 0,
    loginId: 'mech1',
    password: 'password123',
    baseSalary: 35000,
    employmentType: 'PAYROLL'
  },
  {
    id: 'emp-mgr1',
    name: 'Amit Sharma',
    role: 'FLOOR_MANAGER',
    phone: '9820011225',
    email: 'mgr1@workshop.fixocar.com',
    specializedTeam: 'Management',
    status: 'AVAILABLE',
    activeJobsCount: 0,
    loginId: 'mgr1',
    password: 'password123',
    baseSalary: 55000,
    employmentType: 'PAYROLL'
  }
];

export const INITIAL_VENDORS: Vendor[] = [];

export const INITIAL_WORKSHOPS: Workshop[] = [];

export const INITIAL_INVENTORY_ITEMS: InventoryItem[] = [];

export const INITIAL_STANDARD_JOBS: StandardJob[] = [
  {
    id: 'std-bumper-front-full',
    title: 'Front Bumper (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'bumper_front',
    panelNameEn: 'Front Bumper',
    paintScope: 'FULL_OUTER',
    retailPrice: 2200,
    cars24Price: 1350,
    retailPartialPrice: 1300,
    cars24PartialPrice: 800,
    retailInsidePrice: 1100,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2950,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-hood-bonnet-full',
    title: 'Hood / Bonnet (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'hood_bonnet',
    panelNameEn: 'Hood / Bonnet',
    paintScope: 'FULL_OUTER',
    retailPrice: 2500,
    cars24Price: 1350,
    retailPartialPrice: 1500,
    cars24PartialPrice: 800,
    retailInsidePrice: 1250,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 3350,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-fender-lhs-full',
    title: 'Left Front Fender (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'fender_lhs',
    panelNameEn: 'Left Front Fender',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    retailInsidePrice: 900,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2400,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 3
  },
  {
    id: 'std-fender-rhs-full',
    title: 'Right Front Fender (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'fender_rhs',
    panelNameEn: 'Right Front Fender',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    retailInsidePrice: 900,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2400,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 3
  },
  {
    id: 'std-roof-full',
    title: 'Roof Panel (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'roof',
    panelNameEn: 'Roof Panel',
    paintScope: 'FULL_OUTER',
    retailPrice: 3000,
    cars24Price: 1350,
    retailPartialPrice: 1800,
    cars24PartialPrice: 800,
    retailInsidePrice: 1500,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 4000,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 1100,
    retailDenterPayout: 300,
    retailContractorPayout: 1400,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 5
  },
  {
    id: 'std-door-lhs-front-full',
    title: 'Door LHS Front (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_lhs_front',
    panelNameEn: 'Door LHS Front',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-door-lhs-rear-full',
    title: 'Door LHS Rear (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_lhs_rear',
    panelNameEn: 'Door LHS Rear',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-running-board-lhs-full',
    title: 'Running Board LHS / Sill (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'running_board_lhs',
    panelNameEn: 'Running Board LHS / Sill',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    retailInsidePrice: 900,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2400,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 3
  },
  {
    id: 'std-quarter-panel-lhs-full',
    title: 'Quarter Panel LHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'quarter_panel_lhs',
    panelNameEn: 'Quarter Panel LHS',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-door-rhs-front-full',
    title: 'Door RHS Front (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_rhs_front',
    panelNameEn: 'Door RHS Front',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-door-rhs-rear-full',
    title: 'Door RHS Rear (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'door_rhs_rear',
    panelNameEn: 'Door RHS Rear',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-running-board-rhs-full',
    title: 'Running Board RHS / Sill (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'running_board_rhs',
    panelNameEn: 'Running Board RHS / Sill',
    paintScope: 'FULL_OUTER',
    retailPrice: 1800,
    cars24Price: 1350,
    retailInsidePrice: 900,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2400,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 3
  },
  {
    id: 'std-quarter-panel-rhs-full',
    title: 'Quarter Panel RHS (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'quarter_panel_rhs',
    panelNameEn: 'Quarter Panel RHS',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-boot-trunk-full',
    title: 'Boot Lid / Dicky Door (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'boot_trunk',
    panelNameEn: 'Boot Lid / Dicky Door',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-boot-floor-full',
    title: 'Dicky Boot Floor / Underbody (Internal Panel)',
    category: 'PAINT',
    panelKey: 'boot_floor',
    panelNameEn: 'Dicky Boot Floor / Underbody (Internal Panel)',
    paintScope: 'FULL_OUTER',
    retailPrice: 2000,
    cars24Price: 1350,
    retailPartialPrice: 1200,
    cars24PartialPrice: 800,
    retailInsidePrice: 1000,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2700,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  },
  {
    id: 'std-bumper-rear-full',
    title: 'Rear Bumper (Full Outer Paint)',
    category: 'PAINT',
    panelKey: 'bumper_rear',
    panelNameEn: 'Rear Bumper',
    paintScope: 'FULL_OUTER',
    retailPrice: 2200,
    cars24Price: 1350,
    retailPartialPrice: 1300,
    cars24PartialPrice: 800,
    retailInsidePrice: 1100,
    cars24InsidePrice: 675,
    retailFullOuterInsidePrice: 2950,
    cars24FullOuterInsidePrice: 1800,
    isContractBasis: true,
    retailPainterPayout: 950,
    retailDenterPayout: 200,
    retailContractorPayout: 1150,
    cars24PainterPayout: 800,
    cars24DenterPayout: 150,
    cars24ContractorPayout: 950,
    contractorPayout: 950,
    estimatedHours: 4
  }
];

export const INITIAL_DELIVERIES: DeliveryRecord[] = [];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [];

export const INITIAL_JOB_CARDS: JobCard[] = [];

export const INITIAL_VEHICLE_CHECKINS: VehicleCheckIn[] = [];

export const STANDARD_PACKAGES: StandardServicePackage[] = [];
